### ISSUE TITLE
Performance drop using useAnimatedScrollHandler

### ISSUE THREAD

**Issue by owinter86** [software-mansion/react-native-reanimated#1242]
## Description

I am noticing quite a considerable amount of lost frames when using the new useAnimatedScrollHandler hook as opposed to the ReanimatedV1 method, it is especially noticeable when pulling down on iOS and letting go to have the bounce back effect, or scrolling quickly. 

## Steps To Reproduce

reanimatedV2

```
import React from 'react';
import { Dimensions, View } from 'react-native';
import Animated, {
  useAnimatedScrollHandler,
  useAnimatedStyle,
  useSharedValue,
} from 'react-native-reanimated';

const { width } = Dimensions.get('window');

export default function Facets() {
  const translationY = useSharedValue(0);
  const scrollHandler = useAnimatedScrollHandler((event) => {
    translationY.value = event.contentOffset.y;
  });

  const stylez = useAnimatedStyle(() => {
    return {
      transform: [
        {
          translateY: -translationY.value,
        },
      ],
    };
  });

  return (
    <View style={{ flex: 1 }}>
      <Animated.View
        style={[stylez, { position: 'absolute', zIndex: 10, width, height: 200, backgroundColor: 'red' }]}
      />
      <Animated.ScrollView
        contentContainerStyle={{ paddingBottom: 50, paddingTop: 150 }}
        onScroll={scrollHandler}
        scrollEventThrottle={1}
      >
        <View style={{ height: 1000, width }} />
      </Animated.ScrollView>
    </View>
  );
}

```

reanimatedV1
```
import React from 'react';
import { Dimensions, View } from 'react-native';
import Animated from 'react-native-reanimated';

const { width } = Dimensions.get('window');

export default function Facets() {
  const scrollOffset = React.useRef(new Animated.Value(0));
  const stylez = {
    transform: [{ translateY: Animated.multiply(scrollOffset.current, -1) }],
  };

  return (
    <View style={{ flex: 1 }}>
      <Animated.View
        style={[stylez, { position: 'absolute', zIndex: 10, width, height: 200, backgroundColor: 'red' }]}
      />
      <Animated.ScrollView
        contentContainerStyle={{ paddingBottom: 50, paddingTop: 150 }}
        onScroll={Animated.event([{ nativeEvent: { contentOffset: { y: scrollOffset.current } } }])}
        scrollEventThrottle={1}
      >
        <View style={{ height: 1000, width }} />
      </Animated.ScrollView>
    </View>
  );
}
```

## Package versions

```
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-reanimated": "2.0.0-alpha.6",
```

**Comment by terrysahaidak** [comment]
I think this is already resolved in I https://github.com/software-mansion/react-native-reanimated/pull/1215

**Comment by owinter86** [comment]
@terrysahaidak ah nice, I didn't look thoroughly through the master commits it seems, I will patch it locally for now until it reaches the next alpha.

**Comment by terrysahaidak** [comment]
Let us know if it fixes this issue.

**Comment by jakub-gonet** [comment]
Yep, Terry is right. You can try using [prebuilt package (under **NOTE** section)](https://docs.swmansion.com/react-native-reanimated/docs/next/installation#installing-the-package) but please, try it tomorrow 😄 
We had some problems with creating the package due to case-sensitivity issues and it should be resolved in the next build.

Closing this for now, feel free to reopen if update doesn't fix it.

**Comment by Razorholt** [comment]
is there a callback or listener to useAnimatedScrollHandler in ReaminatedV2? Like we have in regular Animated:

```
Animated.event(
   [{ nativeEvent: { contentOffset: { y: scrollY }}}], 
   {
      useNativeDriver: false,
      listener: event => {
      /* some logic */
      }, 
   }
)
```

**Comment by SudoPlz** [comment]
I still experiences that issue in `2.2.2` (on iOS). Shouldn't that be fixed for versions above 2.0.0.alpha?

**Comment by arasrezaei** [comment]
still persist

**Comment by piaskowyk** [comment]
Please check if this issue still occurs in the lates Reanimated 3 version and let me know

**Comment by arasrezaei** [comment]
> Please check if this issue still occurs in the lates Reanimated 3 version and let me know

I'm using Reanimated v3.4.2
I always test it on low android phone like samsung galaxy note 4.
The animation staggering while scrolling.
Maybe because of frame drops.
I've tested default animated.event with native driver and its super smooth.
I will upload a video ...

**Comment by piaskowyk** [comment]
Is it possible for you to provide me a reproduction for this problem? Performance issues are important for me.
