### ISSUE TITLE
selecting Animated components in React DevTools crashes app

### ISSUE THREAD

**Issue by petegivens** [software-mansion/react-native-reanimated#1936]
## Description

When using React DevTools inside of Flipper, my app crashes whenever I select a Component that uses the `useAnimatedStyle` hook.

### Expected behavior

I can inspect all React Components in the React DevTools.

### Actual behavior & steps to reproduce

1. Run app in iOS simulator
2. Open Flipper
3. Select React DevTools
4. Under Components view, select a component that calls `useAnimatedStyle`. (I know that this hook is the culprit because when I comment it out, I can select the component in DevTools).
5. The app crashes in my iOS simulator
6. I've tried with hermes enabled and without. The crash report in Flipper is thousands of lines long and I'm not really sure what to pay attention to, but these seem relevant:

**with hermes enabled**:
```
Crashed Thread: 7 com.facebook.react.JavaScript
Exception Type: EXC_BAD_ACCESS(SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x0000091974615286
Exception Note: EXC_CORPSE_NOTIFY
```
 **without hermes**
```
Crashed Thread:        10  com.facebook.react.JavaScript
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
Assertion failed: (object->ctx_ == ctx_ && "Don't try to clone an object backed by a different Runtime"), function cloneObject, file /Users/petegivens/code/carecomplete/applications/mobile/node_modules/react-native/ReactCommon/jsi/JSCRuntime.cpp, line 611.
```

## Snack or minimal code example

This is enough to make it crash when you select this component in React DevTools:
```
const MyComponent = () => {
  const animatedStyles = useAnimatedStyle(() => {
    return {
      opacity: 0,
    };
  });
  return null;
}
```

## Package versions

- React Native: 0.64.0
- React Native Reanimated: 2.1.0
- NodeJS: 12.19.0
- Xcode: 12.4
- Flipper 0.85.0

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by piaskowyk** [comment]
Hey @petegivens 👋
I think it can be related to this issue: #1923 I fixed this here: #2047 and It should work on the next release - we want to publish it in the next couple of days.

**Comment by piaskowyk** [comment]
Sorry, I must check this again

**Comment by piaskowyk** [comment]
I tested it on the newest version 2.2.0 and it should be ok. Could you check if it works for you also?

**Comment by petegivens** [comment]
@piaskowyk I upgraded reanimated to 2.2.0 but the issue still persists.

**Comment by andrei-zgirvaci-framey** [comment]
@petegivens I had the same issue, upgraded `react-devtools` to **4.13.5** from **4.10.4** and it worked!

Hope it helps!

**Comment by WoLewicki** [comment]
Does this issue still occur in the newest versions of the library or can this be closed?

**Comment by henrilp** [comment]
still occurs

**Comment by jzxchiang1** [comment]
FWIW I get this error not in DevTools but in react-native-vision-camera.

See https://github.com/mrousavy/react-native-vision-camera/discussions/596

I am using RN 0.64.2 and reanimated 2.2.2. Hopefully upgrading to the latest reanimated version can fix it... will try.

**Comment by jzxchiang1** [comment]
FWIW this error only appears in iOS (on an iPhone device).

**Comment by WoLewicki** [comment]
Based on this comment: https://github.com/mrousavy/react-native-vision-camera/discussions/596#discussioncomment-2534264, is this issue resolved in the newest version of reanimated?

**Comment by nandorojo** [comment]
I just got a Sentry report of this happening with Reanimated 2.8.

(Using Expo SDK 45 with a dev client)


<details>
<summary>Here's the error:</summary>

```sh
OS Version: iOS 15.5 (19F77)
Report Version: 104

Exception Type: EXC_CRASH (SIGABRT)
Crashed Thread: 10

Application Specific Information:
Assertion failed: (object->ctx_ == ctx_ && "Don't try to clone an object backed by a different Runtime"), function cloneObject, file JSCRuntime.cpp, line 618.
 > cloneObject > JSCRuntime.cpp > object->ctx_ == ctx_ && "Don't try to clone an object backed by a different Runtime" > receiveEvent

Thread 10 Crashed:
0   libsystem_kernel.dylib          0x3c2f33b38         __pthread_kill
1   libsystem_pthread.dylib         0x435d4d3b8         pthread_kill
2   libsystem_c.dylib               0x369cae520         abort
3   libsystem_c.dylib               0x369d05994         __assert_rtn
4   BeatGig                         0x2029453f0         folly::detail::function::FunctionTraits<T>::uninitCall
5   BeatGig                         0x20273357c         facebook::react::JSIExecutor::defaultTimeoutInvoker
6   BeatGig                         0x20273b370         facebook::react::JSIExecutor::defaultTimeoutInvoker
7   BeatGig                         0x20273e538         facebook::react::JSIExecutor::defaultTimeoutInvoker
8   BeatGig                         0x20273dc2c         facebook::react::JSIExecutor::defaultTimeoutInvoker
9   BeatGig                         0x202731224         facebook::react::JSIExecutor::defaultTimeoutInvoker
10  BeatGig                         0x20267bae4         facebook::react::JSIExecutor::defaultTimeoutInvoker
11  BeatGig                         0x202687fc8         facebook::react::JSIExecutor::defaultTimeoutInvoker
12  BeatGig                         0x202687d7c         facebook::react::JSIExecutor::defaultTimeoutInvoker
13  CoreFoundation                  0x353a025a0         __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__
14  CoreFoundation                  0x353a034fc         __CFRunLoopDoBlocks
15  CoreFoundation                  0x35399b06c         __CFRunLoopRun
16  CoreFoundation                  0x3539aebc4         CFRunLoopRunSpecific
17  BeatGig                         0x20267117c         facebook::react::JSIExecutor::defaultTimeoutInvoker
18  Foundation                      0x3569e1438         __NSThread__start__
19  libsystem_pthread.dylib         0x435d479a8         _pthread_start

Thread 0
0   libsystem_kernel.dylib          0x3c2f2d4a0         mach_msg_trap
1   libsystem_kernel.dylib          0x3c2f2dae0         mach_msg
2   libsystem_kernel.dylib          0x3c2f39a40         thread_suspend
3   BeatGig                         0x20279fb70         facebook::react::JSIExecutor::defaultTimeoutInvoker
4   BeatGig                         0x2027a2804         __cxa_throw
5   libsystem_platform.dylib        0x435d37c0c         _sigtramp
6   libsystem_pthread.dylib         0x435d4d3b8         pthread_kill
7   libsystem_c.dylib               0x369cae520         abort
8   libsystem_c.dylib               0x369d05994         __assert_rtn
9   BeatGig                         0x2029453f0         folly::detail::function::FunctionTraits<T>::uninitCall
10  BeatGig                         0x20273357c         facebook::react::JSIExecutor::defaultTimeoutInvoker
11  BeatGig                         0x202737f58         facebook::react::JSIExecutor::defaultTimeoutInvoker
12  BeatGig                         0x202608508         folly::detail::str_to_integral<T>
13  BeatGig                         0x202735220         facebook::react::JSIExecutor::defaultTimeoutInvoker
14  JavaScriptCore                  0x36a2ba110         JSC::JSCallbackObject<T>::getOwnPropertySlot
15  JavaScriptCore                  0x36ab3a1ec         JSC::LLInt::performLLIntGetByID
16  JavaScriptCore                  0x36ab387d4         llint_slow_path_get_by_id
17  JavaScriptCore                  0x36a222eb8         llint_function_for_construct_arity_checkTagGateAfter
18  JavaScriptCore                  0x36a21442c         vmEntryToJavaScriptTrampoline
19  JavaScriptCore                  0x36aa11e18         JSC::Interpreter::executeCall
20  JavaScriptCore                  0x36ac99388         JSC::profiledCall
21  JavaScriptCore                  0x36a2d1564         JSObjectCallAsFunction
22  BeatGig                         0x202734ad4         facebook::react::JSIExecutor::defaultTimeoutInvoker
23  BeatGig                         0x2026372e8         folly::detail::str_to_integral<T>
24  BeatGig                         0x2027368b4         facebook::react::JSIExecutor::defaultTimeoutInvoker
25  BeatGig                         0x2027365fc         facebook::react::JSIExecutor::defaultTimeoutInvoker
26  JavaScriptCore                  0x36a2be024         JSC::callJSNonFinalObjectCallbackObject
27  JavaScriptCore                  0x36a2145dc         vmEntryToNative
28  JavaScriptCore                  0x36aa11e68         JSC::Interpreter::executeCall
29  JavaScriptCore                  0x36ac99388         JSC::profiledCall
30  JavaScriptCore                  0x36a2d1564         JSObjectCallAsFunction
31  BeatGig                         0x202734ad4         facebook::react::JSIExecutor::defaultTimeoutInvoker
32  BeatGig                         0x202607bbc         folly::detail::str_to_integral<T>
33  BeatGig                         0x20263039c         folly::detail::str_to_integral<T>
34  libdispatch.dylib               0x35338be68         _dispatch_call_block_and_release
35  libdispatch.dylib               0x35338da2c         _dispatch_client_callout
36  libdispatch.dylib               0x35339bf44         _dispatch_main_queue_drain
37  libdispatch.dylib               0x35339bb94         _dispatch_main_queue_callback_4CF
38  CoreFoundation                  0x3539e17fc         __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
39  CoreFoundation                  0x35399b700         __CFRunLoopRun
40  CoreFoundation                  0x3539aebc4         CFRunLoopRunSpecific
41  GraphicsServices                0x38bc33370         GSEventRunModal
42  UIKitCore                       0x358798644         -[UIApplication _run]
43  UIKitCore                       0x358519d8c         UIApplicationMain
44  BeatGig                         0x20244f6f4         <redacted>
45  <unknown>                       0x102de5ce4         <redacted>

Thread 1
0   libsystem_kernel.dylib          0x3c2f2da74         __workq_kernreturn
1   libsystem_pthread.dylib         0x435d47104         _pthread_wqthread

Thread 2
0   libsystem_kernel.dylib          0x3c2f2da74         __workq_kernreturn
1   libsystem_pthread.dylib         0x435d47104         _pthread_wqthread

Thread 3
0   libsystem_kernel.dylib          0x3c2f2da74         __workq_kernreturn
1   libsystem_pthread.dylib         0x435d47104         _pthread_wqthread

Thread 4
0   libsystem_kernel.dylib          0x3c2f2da74         __workq_kernreturn
1   libsystem_pthread.dylib         0x435d47104         _pthread_wqthread

Thread 5
0   libsystem_kernel.dylib          0x3c2f2da74         __workq_kernreturn
1   libsystem_pthread.dylib         0x435d47104         _pthread_wqthread

Thread 6 name: com.apple.uikit.eventfetch-thread
0   libsystem_kernel.dylib          0x3c2f2d4a0         mach_msg_trap
1   libsystem_kernel.dylib          0x3c2f2dae0         mach_msg
2   CoreFoundation                  0x353996d2c         __CFRunLoopServiceMachPort
3   CoreFoundation                  0x35399b1b8         __CFRunLoopRun
4   CoreFoundation                  0x3539aebc4         CFRunLoopRunSpecific
5   Foundation                      0x356991460         -[NSRunLoop(NSRunLoop) runMode:beforeDate:]
6   Foundation                      0x3569d2e28         -[NSRunLoop(NSRunLoop) runUntilDate:]
7   UIKitCore                       0x35871276c         -[UIEventFetcher threadMain]
8   Foundation                      0x3569e1438         __NSThread__start__
9   libsystem_pthread.dylib         0x435d479a8         _pthread_start

Thread 7
0   libsystem_kernel.dylib          0x3c2f2da74         __workq_kernreturn
1   libsystem_pthread.dylib         0x435d47104         _pthread_wqthread

Thread 8
0   libsystem_kernel.dylib          0x3c2f2da74         __workq_kernreturn
1   libsystem_pthread.dylib         0x435d47104         _pthread_wqthread

Thread 9
0   libsystem_kernel.dylib          0x3c2f2da74         __workq_kernreturn
1   libsystem_pthread.dylib         0x435d47104         _pthread_wqthread

Thread 10 name: com.facebook.react.JavaScript Crashed:
0   libsystem_kernel.dylib          0x3c2f33b38         __pthread_kill
1   libsystem_pthread.dylib         0x435d4d3b8         pthread_kill
2   libsystem_c.dylib               0x369cae520         abort
3   libsystem_c.dylib               0x369d05994         __assert_rtn
4   BeatGig                         0x2029453f0         folly::detail::function::FunctionTraits<T>::uninitCall
5   BeatGig                         0x20273357c         facebook::react::JSIExecutor::defaultTimeoutInvoker
6   BeatGig                         0x20273b370         facebook::react::JSIExecutor::defaultTimeoutInvoker
7   BeatGig                         0x20273e538         facebook::react::JSIExecutor::defaultTimeoutInvoker
8   BeatGig                         0x20273dc2c         facebook::react::JSIExecutor::defaultTimeoutInvoker
9   BeatGig                         0x202731224         facebook::react::JSIExecutor::defaultTimeoutInvoker
10  BeatGig                         0x20267bae4         facebook::react::JSIExecutor::defaultTimeoutInvoker
11  BeatGig                         0x202687fc8         facebook::react::JSIExecutor::defaultTimeoutInvoker
12  BeatGig                         0x202687d7c         facebook::react::JSIExecutor::defaultTimeoutInvoker
13  CoreFoundation                  0x353a025a0         __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__
14  CoreFoundation                  0x353a034fc         __CFRunLoopDoBlocks
15  CoreFoundation                  0x35399b06c         __CFRunLoopRun
16  CoreFoundation                  0x3539aebc4         CFRunLoopRunSpecific
17  BeatGig                         0x20267117c         facebook::react::JSIExecutor::defaultTimeoutInvoker
18  Foundation                      0x3569e1438         __NSThread__start__
19  libsystem_pthread.dylib         0x435d479a8         _pthread_start

Thread 11 name: JavaScriptCore libpas scavenger
0   libsystem_kernel.dylib          0x3c2f2df24         __psynch_cvwait
1   libsystem_pthread.dylib         0x435d4e294         _pthread_cond_wait
2   JavaScriptCore                  0x369f26274         scavenger_thread_main
3   libsystem_pthread.dylib         0x435d479a8         _pthread_start

Thread 12 name: Heap Helper Thread
0   libsystem_kernel.dylib          0x3c2f2df24         __psynch_cvwait
1   libsystem_pthread.dylib         0x435d4e294         _pthread_cond_wait
2   JavaScriptCore                  0x369e87310         WTF::ParkingLot::parkConditionallyImpl
3   JavaScriptCore                  0x369e4c444         WTF::Condition::waitUntilUnchecked<T>
4   JavaScriptCore                  0x369e4c8cc         WTF::Detail::CallableWrapper<T>::call
5   JavaScriptCore                  0x369ea84b4         WTF::Thread::entryPoint
6   JavaScriptCore                  0x369eaa7c0         WTF::wtfThreadEntryPoint
7   libsystem_pthread.dylib         0x435d479a8         _pthread_start

Thread 13 name: Heap Helper Thread
0   libsystem_kernel.dylib          0x3c2f2df24         __psynch_cvwait
1   libsystem_pthread.dylib         0x435d4e294         _pthread_cond_wait
2   JavaScriptCore                  0x369e87310         WTF::ParkingLot::parkConditionallyImpl
3   JavaScriptCore                  0x369e4c444         WTF::Condition::waitUntilUnchecked<T>
4   JavaScriptCore                  0x369e4c8cc         WTF::Detail::CallableWrapper<T>::call
5   JavaScriptCore                  0x369ea84b4         WTF::Thread::entryPoint
6   JavaScriptCore                  0x369eaa7c0         WTF::wtfThreadEntryPoint
7   libsystem_pthread.dylib         0x435d479a8         _pthread_start

Thread 14 name: Heap Helper Thread
0   libsystem_kernel.dylib          0x3c2f2df24         __psynch_cvwait
1   libsystem_pthread.dylib         0x435d4e294         _pthread_cond_wait
2   JavaScriptCore                  0x369e87310         WTF::ParkingLot::parkConditionallyImpl
3   JavaScriptCore                  0x369e4c444         WTF::Condition::waitUntilUnchecked<T>
4   JavaScriptCore                  0x369e4c8cc         WTF::Detail::CallableWrapper<T>::call
5   JavaScriptCore                  0x369ea84b4         WTF::Thread::entryPoint
6   JavaScriptCore                  0x369eaa7c0         WTF::wtfThreadEntryPoint
7   libsystem_pthread.dylib         0x435d479a8         _pthread_start

Thread 15 name: Heap Helper Thread
0   libsystem_kernel.dylib          0x3c2f2df24         __psynch_cvwait
1   libsystem_pthread.dylib         0x435d4e294         _pthread_cond_wait
2   JavaScriptCore                  0x369e87310         WTF::ParkingLot::parkConditionallyImpl
3   JavaScriptCore                  0x369e4c444         WTF::Condition::waitUntilUnchecked<T>
4   JavaScriptCore                  0x369e4c8cc         WTF::Detail::CallableWrapper<T>::call
5   JavaScriptCore                  0x369ea84b4         WTF::Thread::entryPoint
6   JavaScriptCore                  0x369eaa7c0         WTF::wtfThreadEntryPoint
7   libsystem_pthread.dylib         0x435d479a8         _pthread_start

Thread 16 name: Heap Helper Thread
0   libsystem_kernel.dylib          0x3c2f2df24         __psynch_cvwait
1   libsystem_pthread.dylib         0x435d4e294         _pthread_cond_wait
2   JavaScriptCore                  0x369e87310         WTF::ParkingLot::parkConditionallyImpl
3   JavaScriptCore                  0x369e4c444         WTF::Condition::waitUntilUnchecked<T>
4   JavaScriptCore                  0x369e4c8cc         WTF::Detail::CallableWrapper<T>::call
5   JavaScriptCore                  0x369ea84b4         WTF::Thread::entryPoint
6   JavaScriptCore                  0x369eaa7c0         WTF::wtfThreadEntryPoint
7   libsystem_pthread.dylib         0x435d479a8         _pthread_start

Thread 17
0   libsystem_kernel.dylib          0x3c2f2da2c         __semwait_signal
1   libsystem_c.dylib               0x369c930e0         nanosleep
2   libsystem_c.dylib               0x369ca7384         sleep
3   BeatGig                         0x202794ed8         facebook::react::JSIExecutor::defaultTimeoutInvoker
4   libsystem_pthread.dylib         0x435d479a8         _pthread_start

Thread 18 name: SentryCrash Exception Handler (Secondary)
0   libsystem_kernel.dylib          0x3c2f2d4a0         mach_msg_trap
1   libsystem_kernel.dylib          0x3c2f2dae0         mach_msg
2   libsystem_kernel.dylib          0x3c2f39a40         thread_suspend
3   BeatGig                         0x2027a1c18         __cxa_throw
4   libsystem_pthread.dylib         0x435d479a8         _pthread_start

Thread 19 name: SentryCrash Exception Handler (Primary)
0   libsystem_kernel.dylib          0x3c2f2d4a0         mach_msg_trap
1   libsystem_kernel.dylib          0x3c2f2dae0         mach_msg
2   BeatGig                         0x2027a1c44         __cxa_throw
3   libsystem_pthread.dylib         0x435d479a8         _pthread_start

Thread 20 name: io.sentry.anr-tracker
0   libsystem_kernel.dylib          0x3c2f2da2c         __semwait_signal
1   libsystem_c.dylib               0x369c930e0         nanosleep
2   Foundation                      0x3569f3d04         +[NSThread sleepForTimeInterval:]
3   BeatGig                         0x20278928c         facebook::react::JSIExecutor::defaultTimeoutInvoker
4   Foundation                      0x3569e1438         __NSThread__start__
5   libsystem_pthread.dylib         0x435d479a8         _pthread_start

Thread 21 name: JSC Heap Collector Thread
0   libsystem_kernel.dylib          0x3c2f2df24         __psynch_cvwait
1   libsystem_pthread.dylib         0x435d4e294         _pthread_cond_wait
2   JavaScriptCore                  0x369e87310         WTF::ParkingLot::parkConditionallyImpl
3   JavaScriptCore                  0x369e4c444         WTF::Condition::waitUntilUnchecked<T>
4   JavaScriptCore                  0x369e4c8cc         WTF::Detail::CallableWrapper<T>::call
5   JavaScriptCore                  0x369ea84b4         WTF::Thread::entryPoint
6   JavaScriptCore                  0x369eaa7c0         WTF::wtfThreadEntryPoint
7   libsystem_pthread.dylib         0x435d479a8         _pthread_start

Thread 22 name: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib          0x3c2f2d4a0         mach_msg_trap
1   libsystem_kernel.dylib          0x3c2f2dae0         mach_msg
2   CoreFoundation                  0x353996d2c         __CFRunLoopServiceMachPort
3   CoreFoundation                  0x35399b1b8         __CFRunLoopRun
4   CoreFoundation                  0x3539aebc4         CFRunLoopRunSpecific
5   CFNetwork                       0x354c46238         _CFURLStorageSessionDisableCache
6   Foundation                      0x3569e1438         __NSThread__start__
7   libsystem_pthread.dylib         0x435d479a8         _pthread_start
```

</details>
