### ISSUE TITLE
App does not build because of react-native-reanimated

### ISSUE THREAD

**Issue by martmists-gh** [software-mansion/react-native-reanimated#2045]
## Description

When compiling my app, React Native Reanimated gives an error in the build.gradle file:

```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/home/mart/git/community_app_github/node_modules/react-native-reanimated/android/build.gradle' line: 21

* What went wrong:
A problem occurred evaluating project ':react-native-reanimated'.
> Plugin with id 'maven' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-reanimated'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0/userguide/command_line_interface.html#sec:command_line_warnings

```

I tried running `npm update --force`, but this gave an error of `abs` not being defined, with no js source files I can find.

## Package versions

- React Native: ^0.63.4
- React Native Reanimated: ^1.8.0
- NodeJS: 12.16.1
- Xcode: N/A
- Java & Gradle: Java 16 (java-16-jdk), Gradle 7.0

## Affected platforms

- [x] Android

**Comment by martmists-gh** [comment]
I mean I could add those sections in but it wouldn't provide any meaningful information.

**Comment by jakub-gonet** [comment]
Have you tried removing caches after you installed new version of reanimated? Problem you encountered is fixed in newer versions, make sure you ran gradle clean, ran yarn start --reset-cache and removed node_modules if necessary.

**Comment by martmists-gh** [comment]
Do I need to install yarn for that?

**Comment by martmists-gh** [comment]
gradle clean failed because of the above error, I ran npm update, removed node_modules, npm install, and then tried to assembleRelease again, same error.

**Comment by jakub-gonet** [comment]
> Do I need to install yarn for that?

No, I didn't catch that you're using npm since most RN apps are using yarn.

> I tried running npm update --force, but this gave an error of abs not being defined, with no js source files I can find.

So you managed to get past Gradle install and Metro server was using a stale cache. Try running your app with `npm run start --reset-cache` or manually adding `--reset-cache` flag in the package.json in `start` script section.

> gradle clean failed because of the above error, I ran npm update, removed node_modules, npm install, and then tried to assembleRelease again, same error.

Did you check if Reanimated version was in fact bumped to a newer one?

**Comment by martmists-gh** [comment]
It got updated to ^1.13.3, and while it does load now, it still crashes in gradle.

**Comment by martmists-gh** [comment]
So it seems the `maven` plugin is deprecated in gradle 7, but gradle 6.8.3 does not seem to support java 16

**Comment by jakub-gonet** [comment]
We may need to drop or bump this plugin then. Seems like as a workaround you need to downgrade your Gradle and Java version (if possible).

**Comment by Szymon20000** [comment]
Reanimated is not compatible with gradle 7 right now. Is RN compatible?

**Comment by lijinghuigit** [comment]
请问是怎么解决的这个问题，降低gradle的版本吗

**Comment by piaskowyk** [comment]
Unfortunately, we no longer support Reanimated v1 :/

**Comment by ZeeshanAhmadKhalil** [comment]
I am downgrading to reanimate 1 because we can't do debugging in  reanimate 2
But i am facing the same error

**Comment by TayyabaAslam3317** [comment]
Was anyone able to fix this issue?

**Comment by CyxouD** [comment]
I've fixed this with the solution to downgrade the Gradle from 7 to 6.8.1 as noted here 
https://github.com/expo/expo/issues/12774#issuecomment-839400861

**Comment by SamiChab** [comment]
Until version 1.13.3, react-native reanimated didn't support Gradle 7+. But [since version `1.13.4` it's possible](https://github.com/software-mansion/react-native-reanimated/compare/1.13.3...1.13.4) !
`yarn add react-native-reanimated@1.13.4`

**Comment by khokanuzzman** [comment]
> Until version 1.13.3, react-native reanimated didn't support Gradle 7+. But [since version `1.13.4` it's possible](https://github.com/software-mansion/react-native-reanimated/compare/1.13.3...1.13.4) ! `yarn add react-native-reanimated@1.13.4`

working...

**Comment by sadikyalcin** [comment]
> Unfortunately, we no longer support Reanimated v1 :/

Not every module out there supports hermes yet. You can't just drop support for god knows how many production apps still using v1. I've been stuck for 2 days now and it doesn't look like I'm making any progress what so ever.

**Comment by BFMarks** [comment]
Downgrading to `yarn add react-native-reanimated@1.13.4`  will cause other issues like:

```
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :react-native-screens.
     Required by:
         project :app
      > No matching configuration of project :react-native-screens was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' but:
          - None of the consumable configurations have attributes.

```

**Comment by BFMarks** [comment]
Should have built in Flutter

**Comment by joseito-terence** [comment]
I'm getting this error, during eas build

"expo": "^44.0.0",
"react-native": "0.64.3",
"react-native-reanimated": "~2.3.1",

/home/expo/workingdir/build/apps/geopods-mobile-app/node_modules/react-native-reanimated/android/../../react-native/package.json (No such file or directory)

**Comment by sarmadkung** [comment]
> I'm getting this error, during eas build
> 
> "expo": "^44.0.0", "react-native": "0.64.3", "react-native-reanimated": "~2.3.1",
> 
> /home/expo/workingdir/build/apps/mobile-app/node_modules/react-native-reanimated/android/../../react-native/package.json (No such file or directory)

I am getting same error during android build using `eas build`

Environment
```
"expo": "^46.0.0",
"moti": "~0.20.0",
"react-native-reanimated": "2.9.1",

```
Error
```
Build file '/private/var/folders/r3/ynk8sm4x4znf3b_b91qj284c0000gn/T/eas-build-local-nodejs/bd4197c7-4406-4630-9e35-0530097faa37/build/apps/expo/node_modules/react-native-reanimated/android/build.gradle' line: 216
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] A problem occurred evaluating project ':react-native-reanimated'.
[RUN_GRADLEW] >
[RUN_GRADLEW] /private/var/folders/r3/ynk8sm4x4znf3b_b91qj284c0000gn/T/eas-build-local-nodejs/bd4197c7-4406-4630-9e35-0530097faa37/build/apps/expo/node_modules/react-native/package.json (No such file or directory)

```

**Comment by hugoh59** [comment]
Getting error 

````
* What went wrong:
A problem occurred evaluating project ':react-native-reanimated'.
> Plugin with id 'maven' not found.
````

after upgrading my react native version to 0.70.6, using "react-native-reanimated": "^1.9.0"

**Comment by BogdanRad** [comment]
@hugoh59 I have same problem.. Did you find a solution?

**Comment by hugoh59** [comment]
No :/

**Comment by hugoh59** [comment]
@jakub-gonet Seriously we need your help here. Been stuck on this issue for over a week.

**Comment by qroac** [comment]
I have a simmilar issue like @sarmadkung using expo v45 and react-native-reanimated v2.8.0.
I tried with v.2.13.0 as noted by @BogdanRad, but it made no difference.

What struggles me most:
I tried to repeat a repository version that already worked on Nov. 21, and now it failed, too.
The only difference I can find in expo build logs is, when my build was successful, the worker reported to have node v16.13.2. Now it has v16.18.1.
So it seems there was an update to the used worker images for android builds.

Here is my forum post on expo. Hope to find out more soon.
https://forums.expo.dev/t/gradlew-job-fails-to-resolve-react-native-monorepo-build-already-worked-on-nov-21/68274/2

**Comment by skngetich** [comment]
After countless trials, I solved this issue and understood how it could occur. Below are some of the steps that help resolve the issue
1. Check if the gradle version is compatible with JDK installed. if there is a [mismatch](https://docs.gradle.org/current/userguide/compatibility.html#:~:text=A%20Java%20version%20between%208,be%20supported%20in%20Gradle%209.0.). In react native documentation, it recommends JDK version 11.   
2. Check if the JAVA_HOME environment variable is set correctly.
3. If the project uses react-native above version 0.60.0, run `npx jetify` in the root of the project before building it with gradle or running the `react-native run android`. jetify convert node_modules dependencies to AndroidX

**Comment by gianencoder** [comment]
> 

That works for me!, I had the same problem. With npm run start --reset-cache works. Thank you !
