### ISSUE TITLE
AnimatedLayout breaking iOS touch when using with react-native-modal

### ISSUE THREAD

**Issue by raulmax319** [software-mansion/react-native-reanimated#2279]
## Description

Problem with reanimated 2 AnimatedLayout when using with react-native-modal library

### Expected behavior

The Modal opens inside a `AnimatedLayout` component, and when you close it the touch does not stop working

### Actual behavior & steps to reproduce

When you toggle the modal inside a `AnimatedLayout` it disables all touch events on the app
To reproduce this issue you need
`@react-navigation/native@5.9.4`
`@react-navigation/stack@5.14.5` 
`react-native-reanimated@2.3.0-alpha.1`
`react-native-modal@12.0.3`
```yarn```
You also need to fix the problem related to the issue #2124 so it won't break when initializing the app
```
cd ios && pod install
cd .. && yarn ios
```

## Snack or minimal code example
You can see all the code by following the link bellow:
https://github.com/raulmax319/react-native-typescript-redux-boilerplate/tree/repro/rn-modal

This is a example video of the actual behavior

https://user-images.githubusercontent.com/17752968/129127972-a3fdd287-b88b-44bb-b845-a0cc0f5023d8.mov

## Package versions

- React Native: 0.64.1
- React Native Reanimated: 2.3.0-alpha.1
- NodeJS: 16.1.0
- Xcode: 12.5.1

## Affected platforms

- [ ] Android
- [ X ] iOS
- [ ] Web

**Comment by jmysliv** [comment]
Hi @raulmax319 ! We have just released `2.3.0-alpha.3` without `AnimatedLayout` and I think your problem might be gone. Can you check it and let me know?

**Comment by raulmax319** [comment]
Hello @jmysliv ! I tried updating my project and removed the `AnimatedLayout` component to a common `View` but it didn't seem to work, sadly, now the problem seems to persist even if the `<Modal />` is outside the `Container` scope (wrapped inside a fragment as shown in the example video), because now there's no `AnimatedLayout` to wrap it. I tried switching from `react-native-modal` to `react-native`'s modal but it had the same effect as the lib uses the same component but is a bit more customizable.
I also updated the repo's rn version to `0.65.1` and reanimated's ver. to `2.3.0-alpha.3`

**Comment by raulmax319** [comment]
On another note, I tried building on my android phone as a safety measure, but now when I build it I get the following error screen: 

![resized-screenshot](https://user-images.githubusercontent.com/17752968/132110501-4d969310-893f-4dc4-b84f-5dd7582453e8.jpeg)

**Comment by piaskowyk** [comment]
The reason for the problem with null ptr is probably the same as in #2369

But I can confirm that problem with modal still exists on alpha.3

**Comment by raulmax319** [comment]
Hello, 
I've come with a workaround by using the `@react-navigation` transparent modal.

I just had to not navigate inside an asynchronous function, I can use the application normally if I navigate inside synchronous functions, not async ones.

I still don't know the reason for that and I still need to send API calls on some modals so it's not a solution, but I can work with this until this is solved.

**Comment by raulmax319** [comment]
Thank you very much!!
