### ISSUE TITLE
"Attempting to assign to readonly property" error when using SharedValue across Runtimes (VisionCamera) (interpolateColor: `getInterpolateCacheRGBA`)

### ISSUE THREAD

**Issue by mrousavy** [software-mansion/react-native-reanimated#2329]
## Description

I'm using this hook:

```tsx
export function useAnimatedColor(
  color: Reanimated.SharedValue<string>,
): Readonly<Reanimated.SharedValue<string | number>> {
  const animation = useSharedValue(0);
  const colorFrom = useSharedValue(DEFAULT_COLOR);
  const colorTo = useSharedValue(color.value);

  useAnimatedReaction(
    () => color.value,
    (newColor, prevColor) => {
      animation.value = 0;
      colorFrom.value = prevColor ?? DEFAULT_COLOR;
      colorTo.value = newColor;
      animation.value = withTiming(1, {
        duration: 150,
        easing: Easing.linear,
      });
      console.log(`Animating from ${prevColor} -> ${newColor}`);
    },
  );

  // TODO: Using colorFrom and colorTo in here raises "Attempting to assign to readonly property" error...
  return useDerivedValue(() =>
    interpolateColor(animation.value, [0, 1], [colorFrom.value, colorTo.value]),
  );
}
```

which results in this error being thrown:

<img src="https://user-images.githubusercontent.com/15199031/131217075-9057e642-d168-452f-adfe-9702def61294.jpeg" width="55%" />

### Expected behavior

I expect it to interpolate correctly

### Actual behavior & steps to reproduce

It crashes

## Snack or minimal code example

https://github.com/mrousavy/Colorwaver ([this code](https://github.com/mrousavy/Colorwaver/blob/40bccf92f1533f08be7be4e425f3fa3b8b30ed28/src/useAnimatedColor.ts#L32-L35) throws the error. the passed in SharedValue is being assigned [here](https://github.com/mrousavy/Colorwaver/blob/40bccf92f1533f08be7be4e425f3fa3b8b30ed28/src/App.tsx#L37-L44))

## Package versions

- React Native: 0.65.1
- React Native Reanimated: 2.3.0-alpha.2
- NodeJS: 14
- Xcode: /
- Java & Gradle: /

## Affected platforms

- [ ] Android (not tested)
- [x] iOS
- [ ] Web (not tested)

**Comment by mrousavy** [comment]
(Stacktrace points to the  `getInterpolateCacheRGBA` function) https://github.com/software-mansion/react-native-reanimated/blob/d6476f3557651c2f5e5add449f0d1e4e63bd25d1/src/reanimated2/Colors.ts#L693-L726

**Comment by mrousavy** [comment]
Yep, suspicion confirmed. If I remove the caching completely, everything runs smoothly:

```diff
 const getInterpolateCacheRGBA = ( 
   colors: readonly (string | number)[] 
 ): InterpolateCacheRGBA => { 
   'worklet'; 
   const hash = colors.join(''); 
   const cache = interpolateCacheRGBA[hash]; 
-  if (cache !== undefined) { 
-    return cache; 
-  } 
  
   const r = []; 
   const g = []; 
   const b = []; 
   const a = []; 
   for (let i = 0; i < colors.length; ++i) { 
     const color = colors[i]; 
     const proocessedColor = processColor(color); 
     if (proocessedColor) { 
       r.push(red(proocessedColor)); 
       g.push(green(proocessedColor)); 
       b.push(blue(proocessedColor)); 
       a.push(opacity(proocessedColor)); 
     } 
   } 
   const newCache = { r, g, b, a }; 
-  const overrideHash = hashOrderRGBA[curentHashIndexRGBA]; 
-  if (overrideHash) { 
-    delete interpolateCacheRGBA[overrideHash]; 
-  } 
-  interpolateCacheRGBA[hash] = newCache; 
-  hashOrderRGBA[curentHashIndexRGBA] = hash; 
-  curentHashIndexRGBA = (curentHashIndexRGBA + 1) % BUFFER_SIZE; 
   return newCache; 
 }; 
```

**Comment by justblender** [comment]
Any updates on this issue?

**Comment by gersomvg** [comment]
I have this same error with RN 0.66 and reanimated 2.3.0-beta.2

**Comment by ThasianX** [comment]
good catch on the cache issue. it's a decent hotfix for now. can someone take a deeper look as to why the caching is a cause for crashes?

**Comment by gersomvg** [comment]
This is fixed with reanimated 2.2.4 btw, which also works with rn 0.66.0

**Comment by maitriyogin** [comment]
I'm getting this as well, tried the patch to no avail..

**Comment by ThasianX** [comment]
> This is fixed with reanimated 2.2.4 btw, which also works with rn 0.66.0
> 
> (Or this issue was never introduced in that minor version to begin with 😅 )

works! thank you

**Comment by maitriyogin** [comment]
Thx

**Comment by filipengberg** [comment]
I got the same error on iOS using `react-native-reanimated@2.3.0-beta.3` and `react-native@0.66.1`. 

I fixed of the error by enabling hermes in the Podfile and running `npx pod-install`

**Comment by maitriyogin** [comment]
Was enabling Hermes the fix?

**Comment by filipengberg** [comment]
For me, yes!

**Comment by faroutchris** [comment]
Enabling hermes fixed this issue for me as well. Running on `"react-native": "0.64.3"` & `"react-native-reanimated": "~2.3.1",`

**Comment by magrinj** [comment]
@piaskowyk Still having the issue on my side, with expo and `react-native-reanimated@~2.3.1`.
Here a snippet of the code:
```typescript
  const focused = useSharedValue(false);
  const progress = useDerivedValue(() =>
    withTiming(focused.value === true ? 1 : 0),
  );

  // Animated style
  const searchIconStyle = useAnimatedStyle(() => ({
    color: interpolateColor(progress.value, [0, 1], ['red', 'green']),
  }));
```
