### ISSUE TITLE
Warning: componentWillMount is deprecated

### ISSUE THREAD

**Issue by vikrantnegi** [software-mansion/react-native-reanimated#353]
## Issue 
I'm receiving a warning about `componentWillMount` is deprecated.

```
Warning: componentWillMount is deprecated and will be removed in the next major version. Use componentDidMount instead. As a temporary workaround, you can rename to UNSAFE_componentWillMount.

Please update the following components: AnimatedComponent

Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks
```

## Versions: 
"react": "16.8.6",
 "react-native": "0.60.4",
"react-native-reanimated": "^1.1.0",

**Comment by jhainaua** [comment]
As a workaround you can go into 'react-native-reanimated/src/core/createAnimatedComponent.js and change `componentWillMount()` to `UNSAFE_componentWillMount()`

I also haven't had any problems with my animations after moving `this._attachProps(this.props);` into the `componentDidMount()` lifecycle method.

**Comment by jbrodriguez** [comment]
@jhainaua, that is not a workable solution, you'd need to change the upstream code every time you reinstall or in CI environments and such.

**Comment by jhainaua** [comment]
@jbrodriguez would creating your own fork and installing that while waiting for a solution not solve the problem you posited?

Regardless, I apologize for the confusion; I believed that starting the comment with "workaround" would have carried the implications through for the rest of the comment. I've since updated the phrase "workable solution," to "workaround that can solve the problem," as "workaround" implies a temporary fix. Hopefully that language is clearer.

Also, after checking some of the pull requests, it looks like a solution is also being discussed in pull request #342 .

**Comment by iwikal** [comment]
Until resolved in upstream, this tool can be used to apply the workaround directly in the `node_modules` directory without having to create a fork: https://github.com/ds300/patch-package

**Comment by cargallo** [comment]
I think that the best workarround, if you know that you are not using ComponentWillMount in your own code, and it's just a library deprecation, is to add an ignore warning at index.js in root directory

import { YellowBox } from 'react-native';

//TODO:CHECK NOT USING THIS LIFECYCLE METHODS. Ignoring change of lifecycle react-native 
YellowBox.ignoreWarnings([
  'Warning: componentWillMount is deprecated',
  'Warning: componentWillReceiveProps is deprecated',
  'Warning: componentWillUpdate is deprecated',
]);

**Comment by paschaldev** [comment]
@cargallo That's not a workaround. It just hides the warning which is not a good thing to do

**Comment by cargallo** [comment]
> @cargallo That's not a workaround. It just hides the warning which is not a good thing to do

Yes It's. The Warning just says that the componentWillMount is deprecated and will be removed in the next major version. Until you change the version of your project you will not have any problem and at that time probably the library will be corrected. That's why I talked about workarround and not solution.

**Comment by nucle4r** [comment]
> @jbrodriguez Until resolved in upstream, this tool can be used to apply the workaround directly in the `node_modules` directory without having to create a fork: https://github.com/ds300/patch-package

Unfortunately this is not helping me! I followed the directions but every time I install a dependency it reverts back.

**Comment by mattmogford** [comment]
The fix has been pushed to master, but isn't on npm yet. I would rather not blanket ignore cpm deprecation warnings, in-case any others come along that could be missed.

**Comment by pistou** [comment]
The fix seems to be merged in `master` branch but not on NPM.
As a *workaround*, you can install the current `master` branch - but you'd lose the version number

```
yarn add https://github.com/kmagiera/react-native-reanimated.git\#master
// OR npm install https://github.com/kmagiera/react-native-reanimated.git\#master
```

**Comment by avasuro** [comment]
@pistou 

You can use commit hash instead of branch to achieve some sort of locking version:
```
yarn add https://github.com/kmagiera/react-native-reanimated.git#cd5a319eb6afd6efe5fb6750f7cef332fd17bdbd
// OR npm install https://github.com/kmagiera/react-native-reanimated.git#cd5a319eb6afd6efe5fb6750f7cef332fd17bdbd
```

**Comment by IntelliJAbhishek** [comment]
Changes has been merged in 1.3.0. You can close this issue.

**Comment by chrisparton1991** [comment]
Thanks for this! I was still getting the warning after upgrading, but clearing the transform cache fixed that:
```
npm start -- --reset-cache
```

**Comment by olamigokayphils** [comment]
Upgrading `react-native-reanimated` should resolve warnings
