### ISSUE TITLE
[iOS] Crash in MutableValue::set

### ISSUE THREAD

**Issue by DanijelBojcic** [software-mansion/react-native-reanimated#3632]
### Description

My app is crashing in production. 
It usually happens at app start. About every 5th app start will end in crash.

The stacktrace I get from crashlytics:
```
Crashed: com.apple.main-thread
0  pierre                         0x27fd74 std::__1::__function::__func<reanimated::MutableValue::set(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&, facebook::jsi::Value const&)::$_2, std::__1::allocator<reanimated::MutableValue::set(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&, facebook::jsi::Value const&)::$_2>, void ()>::operator()() + 580 (shared_ptr.h:580)
1  pierre                         0x2aa1e4 reanimated::Scheduler::triggerUI() + 463 (function.h:463)
2  libdispatch.dylib              0x63094 _dispatch_call_block_and_release + 24
3  libdispatch.dylib              0x64094 _dispatch_client_callout + 16
4  libdispatch.dylib              0x10d44 _dispatch_main_queue_drain + 928
5  libdispatch.dylib              0x10994 _dispatch_main_queue_callback_4CF$VARIANT$mp + 36
6  CoreFoundation                 0x4e0d4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
7  CoreFoundation                 0xb5f8 __CFRunLoopRun + 2544
8  CoreFoundation                 0x1e250 CFRunLoopRunSpecific + 572
9  GraphicsServices               0x1988 GSEventRunModal + 160
10 UIKitCore                      0x4e5a88 -[UIApplication _run] + 1080
11 UIKitCore                      0x27efc8 UIApplicationMain + 336
12 pierre                         0x9020 main + 14 (main.m:14)
13 ???                            0x105d344d0 (Missing)
```

### Steps to reproduce

I can only catch it in debug when opening and closing app rapidly.

### Snack or a link to a repository

-

### Reanimated version

2.10

### React Native version

0.68.2

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Device model

iPhone 13

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @DanijelBojcic, thanks for opening this issue.

Can you please prepare a minimal viable reproduction for this bug?

**Comment by Aximem** [comment]
We're getting the same issue, randomly on release mode only, this is the crash from XCode: 

<img width="1791" alt="Capture d’écran 2022-10-10 à 14 42 20" src="https://user-images.githubusercontent.com/18660012/194869001-dfb1a3e2-b147-4ec8-a63d-abe8554226a1.png">

Seems to be happening when unmounting a component running an animation.

**Comment by DanijelBojcic** [comment]
Unfortunately I do not know how to reproduce it...
One thing I've noticed is that it only happens on iOS 16.

Also maybe I should mention that we are using [react-native-multithreading](https://github.com/mrousavy/react-native-multithreading) / [react-native-vision-camera](https://github.com/mrousavy/react-native-vision-camera)  custom implementation for state management with MMKV, that notifies the JS if there is a change.

I assume the crash comes from rapidly calling `reanimated::ShareableValue::adapt`, when we want to call a JS callback from the JSI

**Comment by mym0404** [comment]
I have no idea this is related to this. But it seems to this is not only iOS16 issue
![image](https://user-images.githubusercontent.com/33388801/195744500-7f4eac8a-867f-43c5-8b7a-649cb14f38ac.png)

**Comment by jinliming2** [comment]
I got the same crash on iPhone XR iOS 15.6.1, which does not reproduce consistently.

![image](https://user-images.githubusercontent.com/10294977/197407529-4e75fa6f-5c98-415f-9107-1fa30583929a.png)

**Comment by jmorey28** [comment]
we are seeing this issue as well iOS 16 only

**Comment by ParthChugh** [comment]
Any Update on this?

**Comment by terribleben** [comment]
I think we are seeing this too. For us, it was from the same JS migration that led to https://github.com/software-mansion/react-native-reanimated/issues/3917 (which contains a repro repository).

We didn't change our package versions at all - just migrated the JS API to use `sharedValue` and `Gesture.Pan`. The exact package versions and code sample are shown in the attached repro repository on that other issue.

After making this change, we started seeing `EXC_BAD_ACCESS (attempted to dereference garbage pointer)` in `reanimated::Scheduler::triggerUI` in our Sentry logs. We deployed this change to a small percentage of our traffic (about 3,000 users) and it affected 1.8% of them, which is severe enough that we'll need to roll back the change.

We've also seen a spike in OOM reports on iOS only, so maybe related to https://github.com/software-mansion/react-native-reanimated/issues/2824, but I don't have any strong evidence of that.

**Comment by levepic** [comment]
Same error here, cannot find the cause. Removed animations from the specific screen where it crashes (according to logs) and strangely still having this issue

**Comment by mtebele** [comment]
Same here:

```
Crashed: com.apple.main-thread
0  appname                          0x19c780 std::__1::__function::__func<reanimated::MutableValue::set(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&, facebook::jsi::Value const&)::$_2, std::__1::allocator<reanimated::MutableValue::set(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&, facebook::jsi::Value const&)::$_2>, void ()>::operator()() + 580 (shared_ptr.h:580)

1  appname                          0x1c1894 reanimated::Scheduler::triggerUI() + 463 (function.h:463)

2  libdispatch.dylib              0x24b4 _dispatch_call_block_and_release + 32

3  libdispatch.dylib              0x3fdc _dispatch_client_callout + 20

4  libdispatch.dylib              0x127f4 _dispatch_main_queue_drain + 928

5  libdispatch.dylib              0x12444 _dispatch_main_queue_callback_4CF + 44

6  CoreFoundation                 0x9a6f8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16

7  CoreFoundation                 0x7c058 __CFRunLoopRun + 2036

8  CoreFoundation                 0x80ed4 CFRunLoopRunSpecific + 612

9  GraphicsServices               0x1368 GSEventRunModal + 164

10 UIKitCore                      0x3a23d0 -[UIApplication _run] + 888

11 UIKitCore                      0x3a2034 UIApplicationMain + 340

12 appname                          0x4ff0 main + 7 (main.m:7)

13 ???                            0x1b2464960 (Falta)
```

**Comment by Dallas62** [comment]
I also attached the issue originaly opened on `react-native-screens`, got many crash from a while when putting the app in background:
![image](https://user-images.githubusercontent.com/3429329/221118164-7a629522-52b3-467c-9f68-60a2cc7f04fe.png)

I do not used custom animation actually, might be a third party library which is calling the buggy part...

**Comment by thibaultfischer** [comment]
Hi, any update on this ?

**Comment by TwistedMinda** [comment]
> I also attached the issue originaly opened on react-native-screens, got many crash from a while when putting the app in background

Same here, we're seeing this issue after the app is put in the background. Don't really know how it's possible but sentry shows a lot of "going to background" logs in a row, without every going back to active mode.

I think we gotta wait : https://github.com/software-mansion/react-native-reanimated/issues/3917

**Comment by jayfeldman12** [comment]
@TwistedMinda in that other thread people said upgrading to reanimated 3 fixes the issue, are you thinking that might do the same here? A stable 3 was released last month so it should be doable.

**Comment by TwistedMinda** [comment]
@jayfeldman12 I think successfully upgrading to reanimated 3 is gonna fix a lot of bug including this one yes, but I still can't confirm this as I'm stuck by another library currently

**Comment by wcastand** [comment]
Hi, i'm on v3 of reanimated and get that issue a lot still, switch to expo-router last week and since then got 1XX crahes and that lead me to here. Only iOS 16 like everyone so not sure v3 would fix this unfortunately :/

![Screenshot 2023-05-29 at 10 50 09](https://github.com/software-mansion/react-native-reanimated/assets/2178244/fc3b8535-cc46-4124-bf3c-31560f618eae)

**Comment by TwistedMinda** [comment]
After successfully migrating to reanimated v3 and react-native 0.71.3 all reanimated-related errors on Sentry are gone for me, an awesome step up

**Comment by maXXCZ1** [comment]
Can anyone else confirm the migration to v3 is viable solution? If so, what react-native version are you running?
We are currently on 0.67.5 (latest version without new architecture) and reanimated 2.4.0. 

We experience problems only on iOS, only in production and we struggle to reproduce it regularly as well. We are currently having two options. Get rid of reanimated completely or migrate it, but migrate whole project to latest RN version (and all libraries) is not an option.

**Comment by tomekzaw** [comment]
@maXXCZ1 Reanimated 3.3.0 is the most stable version ever so I'd recommend upgrading. Let me know if you encounter any problems, we're happy to help.

**Comment by trungledangAxonActive** [comment]
I got the same issue, it's really hard for me to reproduce this.

**Comment by nandorojo** [comment]
I think I may have just gotten this error in prod with RNScreens 3.22 and Reanimated 3.5.4 (RN 0.72.5):

![image](https://github.com/software-mansion/react-native-screens/assets/13172299/8d8e0a99-0f38-4099-a322-adb9c0b1298e)

Does this error seem like it came from Reanimated?

**Comment by tomekzaw** [comment]
@nandorojo "Attempted to dereference garbage pointer" looks familiar but the stack trace doesn't so can't say for sure. Could you send me over the whole stack trace?

**Comment by zhou0506** [comment]
OS Version: iOS 17.2 (21C5054b)
Report Version: 104

Exception Type: EXC_BAD_ACCESS (SIGBUS)
Exception Codes: BUS_NOOP at 0x0000000000000018
Crashed Thread: 0

Application Specific Information:
ZTUM >
Attempted to dereference garbage pointer 0x18.

Thread 0 Crashed:
0   SenseCAPMate                    0x200eecc18         folly::detail::str_to_integral<T>
1   SenseCAPMate                    0x200f14b48         folly::detail::str_to_integral<T>
2   libdispatch.dylib               0x3392ec6a8         <redacted>
3   libdispatch.dylib               0x3392ee300         <redacted>
4   libdispatch.dylib               0x3392fc998         <redacted>
5   libdispatch.dylib               0x3392fc5b0         _dispatch_main_queue_callback_4CF
6   CoreFoundation                  0x32932b01c         <redacted>
7   CoreFoundation                  0x329327d28         <redacted>
8   CoreFoundation                  0x329327478         CFRunLoopRunSpecific
9   Foundation                      0x32725448c         <redacted>
10  Foundation                      0x32728174c         <redacted>
11  SenseCAPMate                    0x2011c00a0         __cxa_throw
12  SenseCAPMate                    0x200d033c8         <redacted>
13  UIKitCore                       0x32d965fd0         <redacted>
14  UIKitCore                       0x32d965138         <redacted>
15  UIKitCore                       0x32d96411c         <redacted>
16  UIKitCore                       0x32d963d68         <redacted>
17  UIKitCore                       0x32d8e0890         _UIScenePerformActionsWithLifecycleActionMask
18  UIKitCore                       0x32d967d64         <redacted>
19  UIKitCore                       0x32d88f700         <redacted>
20  UIKitCore                       0x32d88e178         <redacted>
21  UIKitCore                       0x32d88dae0         <redacted>
22  UIKitCore                       0x32d88d9b0         <redacted>
23  UIKitCore                       0x32d88d8b8         <redacted>
24  UIKitCore                       0x32d88d140         _UISceneSettingsDiffActionPerformChangesWithTransitionContextAndCompletion
25  UIKitCore                       0x32d88cdf0         <redacted>
26  UIKitCore                       0x32dc10314         <redacted>
27  UIKitCore                       0x32d88bf74         <redacted>
28  UIKitCore                       0x32d88bde4         <redacted>
29  UIKitCore                       0x32d9a477c         <redacted>
30  UIKitCore                       0x32d9a4514         <redacted>
31  FrontBoardServices              0x359c436d4         <redacted>
32  FrontBoardServices              0x359c43570         <redacted>
33  FrontBoardServices              0x359c4219c         <redacted>
34  FrontBoardServices              0x359c4df8c         <redacted>
35  libdispatch.dylib               0x3392ee300         <redacted>
36  libdispatch.dylib               0x3392f1d48         <redacted>
37  FrontBoardServices              0x359c3e520         <redacted>
38  FrontBoardServices              0x359c3e4a0         <redacted>
39  FrontBoardServices              0x359c3e378         <redacted>
40  CoreFoundation                  0x32932b12c         <redacted>
41  CoreFoundation                  0x32932a3a8         <redacted>
42  CoreFoundation                  0x329328b5c         <redacted>
43  CoreFoundation                  0x329327898         <redacted>
44  CoreFoundation                  0x329327478         CFRunLoopRunSpecific
45  GraphicsServices                0x3afe594f8         GSEventRunModal
46  UIKitCore                       0x32d981360         <redacted>
47  UIKitCore                       0x32d98099c         UIApplicationMain
48  SenseCAPMate                    0x200d0397c         <redacted>
49  <unknown>                       0x1c42fddcc         <redacted>

Thread 0 Crashed:
0   SenseCAPMate                    0x200eecc18         folly::detail::str_to_integral<T>
1   SenseCAPMate                    0x200f14b48         folly::detail::str_to_integral<T>
2   libdispatch.dylib               0x3392ec6a8         <redacted>
3   libdispatch.dylib               0x3392ee300         <redacted>
4   libdispatch.dylib               0x3392fc998         <redacted>
5   libdispatch.dylib               0x3392fc5b0         _dispatch_main_queue_callback_4CF
6   CoreFoundation                  0x32932b01c         <redacted>
7   CoreFoundation                  0x329327d28         <redacted>
8   CoreFoundation                  0x329327478         CFRunLoopRunSpecific
9   Foundation                      0x32725448c         <redacted>
10  Foundation                      0x32728174c         <redacted>
11  SenseCAPMate                    0x2011c00a0         __cxa_throw
12  SenseCAPMate                    0x200d033c8         <redacted>
13  UIKitCore                       0x32d965fd0         <redacted>
14  UIKitCore                       0x32d965138         <redacted>
15  UIKitCore                       0x32d96411c         <redacted>
16  UIKitCore                       0x32d963d68         <redacted>
17  UIKitCore                       0x32d8e0890         _UIScenePerformActionsWithLifecycleActionMask
18  UIKitCore                       0x32d967d64         <redacted>
19  UIKitCore                       0x32d88f700         <redacted>
20  UIKitCore                       0x32d88e178         <redacted>
21  UIKitCore                       0x32d88dae0         <redacted>
22  UIKitCore                       0x32d88d9b0         <redacted>
23  UIKitCore                       0x32d88d8b8         <redacted>
24  UIKitCore                       0x32d88d140         _UISceneSettingsDiffActionPerformChangesWithTransitionContextAndCompletion
25  UIKitCore                       0x32d88cdf0         <redacted>
26  UIKitCore                       0x32dc10314         <redacted>
27  UIKitCore                       0x32d88bf74         <redacted>
28  UIKitCore                       0x32d88bde4         <redacted>
29  UIKitCore                       0x32d9a477c         <redacted>
30  UIKitCore                       0x32d9a4514         <redacted>
31  FrontBoardServices              0x359c436d4         <redacted>
32  FrontBoardServices              0x359c43570         <redacted>
33  FrontBoardServices              0x359c4219c         <redacted>
34  FrontBoardServices              0x359c4df8c         <redacted>
35  libdispatch.dylib               0x3392ee300         <redacted>
36  libdispatch.dylib               0x3392f1d48         <redacted>
37  FrontBoardServices              0x359c3e520         <redacted>
38  FrontBoardServices              0x359c3e4a0         <redacted>
39  FrontBoardServices              0x359c3e378         <redacted>
40  CoreFoundation                  0x32932b12c         <redacted>
41  CoreFoundation                  0x32932a3a8         <redacted>
42  CoreFoundation                  0x329328b5c         <redacted>
43  CoreFoundation                  0x329327898         <redacted>
44  CoreFoundation                  0x329327478         CFRunLoopRunSpecific
45  GraphicsServices                0x3afe594f8         GSEventRunModal
46  UIKitCore                       0x32d981360         <redacted>
47  UIKitCore                       0x32d98099c         UIApplicationMain
48  SenseCAPMate                    0x200d0397c         <redacted>
49  <unknown>                       0x1c42fddcc         <redacted>

Thread 1
0   libsystem_pthread.dylib         0x3fd30d9fc         _pthread_wqthread

Thread 2
0   libsystem_kernel.dylib          0x3b81816d0         __workq_kernreturn
1   libsystem_pthread.dylib         0x3fd30d9b0         _pthread_wqthread

Thread 3
0   libquic.dylib                   0x4087d9034         <redacted>
1   libquic.dylib                   0x4087d8f98         [inlined] <redacted>
2   libquic.dylib                   0x4087d8f98         <redacted>
3   Network                         0x32a37d9d0         nw_frame_array_foreach
4   libquic.dylib                   0x4087d8f14         <redacted>
5   Network                         0x32a048764         nw_protocol_instance_access_flow_state
6   libquic.dylib                   0x4087d8d78         <redacted>
7   libquic.dylib                   0x4087d8b10         <redacted>
8   libboringssl.dylib              0x38a188228         <redacted>
9   libboringssl.dylib              0x38a1c3d60         <redacted>
10  libboringssl.dylib              0x38a1761e4         <redacted>
11  libboringssl.dylib              0x38a15624c         <redacted>
12  libboringssl.dylib              0x38a163ddc         SSL_do_handshake
13  libboringssl.dylib              0x38a163b38         boringssl_session_handshake_continue
14  libboringssl.dylib              0x38a14b42c         <redacted>
15  libboringssl.dylib              0x38a163aac         <redacted>
16  libboringssl.dylib              0x38a180da0         <redacted>
17  Network                         0x329da8358         nw_queue_context_async_if_needed
18  libboringssl.dylib              0x38a180548         <redacted>
19  CFNetwork                       0x32b5682d0         CFURLDownloadStart
20  CFNetwork                       0x32b685a34         CFHTTPCookieStorageUnscheduleFromRunLoop
21  CFNetwork                       0x32b5575a4         CFURLDownloadStart
22  CFNetwork                       0x32b557248         CFURLDownloadStart
23  libdispatch.dylib               0x3392ec6a8         <redacted>
24  libdispatch.dylib               0x3392ee300         <redacted>
25  libdispatch.dylib               0x3392f5894         <redacted>
26  libdispatch.dylib               0x3392f63f8         <redacted>
27  libdispatch.dylib               0x3392f76a8         <redacted>
28  libdispatch.dylib               0x339301004         <redacted>
29  libdispatch.dylib               0x339300878         <redacted>
30  libsystem_pthread.dylib         0x3fd30d964         _pthread_wqthread

Thread 4 name: com.apple.uikit.eventfetch-thread
0   libsystem_kernel.dylib          0x3b8179178         mach_msg2_trap
1   libsystem_kernel.dylib          0x3b8178f10         mach_msg2_internal
2   libsystem_kernel.dylib          0x3b8178e28         mach_msg_overwrite
3   libsystem_kernel.dylib          0x3b8178c68         mach_msg
4   CoreFoundation                  0x329329b1c         <redacted>
5   CoreFoundation                  0x329327a14         <redacted>
6   CoreFoundation                  0x329327478         CFRunLoopRunSpecific
7   Foundation                      0x32725448c         <redacted>
8   Foundation                      0x32728174c         <redacted>
9   UIKitCore                       0x32d8e30c0         <redacted>
10  Foundation                      0x3272d7de0         <redacted>
11  libsystem_pthread.dylib         0x3fd30e4d4         _pthread_start

Thread 5
0   CoreFoundation                  0x329308758         <redacted>
1   CoreFoundation                  0x3293086a4         <redacted>
2   CoreFoundation                  0x3293f886c         <redacted>
3   CoreFoundation                  0x329309930         <redacted>
4   CoreFoundation                  0x32935cb70         _CFPropertyListCreateFiltered
5   CoreFoundation                  0x32938db34         <redacted>
6   CoreFoundation                  0x32936eefc         <redacted>
7   CoreFoundation                  0x329350264         <redacted>
8   CoreFoundation                  0x32934fb88         _CFBundleCopyLocalizedStringForLocalizationTableURLAndMarkdownOption
9   CFNetwork                       0x32b588b0c         _CFURLWriteDataAndPropertiesToResource
10  CFNetwork                       0x32b588278         _CFURLWriteDataAndPropertiesToResource
11  libsystem_pthread.dylib         0x3fd30f3d4         <redacted>
12  libsystem_platform.dylib        0x3fd1b7eb4         <redacted>
13  libsystem_pthread.dylib         0x3fd30f7a8         pthread_once
14  CFNetwork                       0x32b588188         _CFURLWriteDataAndPropertiesToResource
15  CFNetwork                       0x32b4ae814         _CFNetworkErrorCopyLocalizedDescriptionWithHostname
16  Foundation                      0x3278d73bc         <redacted>
17  Foundation                      0x3278d75f4         <redacted>
18  Foundation                      0x3278d71fc         <redacted>
19  CFNetwork                       0x32b4d8314         CFHTTPMessageCopySerializedMessage
20  libdispatch.dylib               0x3392ec6a8         <redacted>
21  libdispatch.dylib               0x3392ee300         <redacted>
22  libdispatch.dylib               0x3392f5894         <redacted>
23  libdispatch.dylib               0x3392f63f8         <redacted>
24  libdispatch.dylib               0x339301004         <redacted>
25  libdispatch.dylib               0x339300878         <redacted>
26  libsystem_pthread.dylib         0x3fd30d964         _pthread_wqthread

Thread 6
0   libsystem_kernel.dylib          0x3b81790f4         semaphore_wait_trap
1   libdispatch.dylib               0x3392ee89c         <redacted>
2   libdispatch.dylib               0x3392eef4c         <redacted>
3   CFNetwork                       0x32b4b0718         CFURLConnectionSendSynchronousRequest
4   CFNetwork                       0x32b570910         cfnTranslateCFError
5   SenseCAPMate                    0x2012685d0         __cxa_throw
6   SenseCAPMate                    0x201265540         __cxa_throw
7   SenseCAPMate                    0x20126cf54         __cxa_throw
8   libdispatch.dylib               0x3392ec6a8         <redacted>
9   libdispatch.dylib               0x3392ee300         <redacted>
10  libdispatch.dylib               0x3392f144c         <redacted>
11  libdispatch.dylib               0x3392ffbe4         <redacted>
12  libdispatch.dylib               0x3393003ec         <redacted>
13  libsystem_pthread.dylib         0x3fd30d928         _pthread_wqthread

Thread 7
0   libsystem_pthread.dylib         0x3fd30d9fc         _pthread_wqthread

Thread 8
0   libsystem_kernel.dylib          0x3b81816d0         __workq_kernreturn
1   libsystem_pthread.dylib         0x3fd30d9b0         _pthread_wqthread

Thread 9
0   libsystem_pthread.dylib         0x3fd30d9fc         _pthread_wqthread

Thread 10 name: com.facebook.react.JavaScript
0   libsystem_kernel.dylib          0x3b8179178         mach_msg2_trap
1   libsystem_kernel.dylib          0x3b8178f10         mach_msg2_internal
2   libsystem_kernel.dylib          0x3b8178e28         mach_msg_overwrite
3   libsystem_kernel.dylib          0x3b8178c68         mach_msg
4   CoreFoundation                  0x329329b1c         <redacted>
5   CoreFoundation                  0x329327a14         <redacted>
6   CoreFoundation                  0x329327478         CFRunLoopRunSpecific
7   SenseCAPMate                    0x200f682d4         facebook::react::JSIExecutor::defaultTimeoutInvoker
8   Foundation                      0x3272d7de0         <redacted>
9   libsystem_pthread.dylib         0x3fd30e4d4         _pthread_start

Thread 11 name: JavaScriptCore libpas scavenger
0   libsystem_kernel.dylib          0x3b8179b1c         __psynch_cvwait
1   libsystem_pthread.dylib         0x3fd30cfd4         <redacted>
2   JavaScriptCore                  0x355da31a0         <redacted>
3   libsystem_pthread.dylib         0x3fd30e4d4         _pthread_start

Thread 12 name: Heap Helper Thread
0   libsystem_kernel.dylib          0x3b8179b1c         __psynch_cvwait
1   libsystem_pthread.dylib         0x3fd30cfd4         <redacted>
2   JavaScriptCore                  0x354893120         WTF::ThreadCondition::timedWait
3   JavaScriptCore                  0x35486c1d4         WTF::ParkingLot::parkConditionallyImpl
4   JavaScriptCore                  0x35482a728         <redacted>
5   JavaScriptCore                  0x354890334         <redacted>
6   JavaScriptCore                  0x35489280c         <redacted>
7   libsystem_pthread.dylib         0x3fd30e4d4         _pthread_start

Thread 13 name: Heap Helper Thread
0   libsystem_kernel.dylib          0x3b8179b1c         __psynch_cvwait
1   libsystem_pthread.dylib         0x3fd30cfd4         <redacted>
2   JavaScriptCore                  0x354893120         WTF::ThreadCondition::timedWait
3   JavaScriptCore                  0x35486c1d4         WTF::ParkingLot::parkConditionallyImpl
4   JavaScriptCore                  0x35482a728         <redacted>
5   JavaScriptCore                  0x354890334         <redacted>
6   JavaScriptCore                  0x35489280c         <redacted>
7   libsystem_pthread.dylib         0x3fd30e4d4         _pthread_start

Thread 14 name: Heap Helper Thread
0   libsystem_kernel.dylib          0x3b8179b1c         __psynch_cvwait
1   libsystem_pthread.dylib         0x3fd30cfd4         <redacted>
2   JavaScriptCore                  0x354893120         WTF::ThreadCondition::timedWait
3   JavaScriptCore                  0x35486c1d4         WTF::ParkingLot::parkConditionallyImpl
4   JavaScriptCore                  0x35482a728         <redacted>
5   JavaScriptCore                  0x354890334         <redacted>
6   JavaScriptCore                  0x35489280c         <redacted>
7   libsystem_pthread.dylib         0x3fd30e4d4         _pthread_start

Thread 15 name: Heap Helper Thread
0   libsystem_kernel.dylib          0x3b8179b1c         __psynch_cvwait
1   libsystem_pthread.dylib         0x3fd30cfd4         <redacted>
2   JavaScriptCore                  0x354893120         WTF::ThreadCondition::timedWait
3   JavaScriptCore                  0x35486c1d4         WTF::ParkingLot::parkConditionallyImpl
4   JavaScriptCore                  0x35482a728         <redacted>
5   JavaScriptCore                  0x354890334         <redacted>
6   JavaScriptCore                  0x35489280c         <redacted>
7   libsystem_pthread.dylib         0x3fd30e4d4         _pthread_start

Thread 16 name: Heap Helper Thread
0   libsystem_kernel.dylib          0x3b8179b1c         __psynch_cvwait
1   libsystem_pthread.dylib         0x3fd30cfd4         <redacted>
2   JavaScriptCore                  0x354893120         WTF::ThreadCondition::timedWait
3   JavaScriptCore                  0x35486c1d4         WTF::ParkingLot::parkConditionallyImpl
4   JavaScriptCore                  0x35482a728         <redacted>
5   JavaScriptCore                  0x354890334         <redacted>
6   JavaScriptCore                  0x35489280c         <redacted>
7   libsystem_pthread.dylib         0x3fd30e4d4         _pthread_start

Thread 17 name: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib          0x3b8179178         mach_msg2_trap
1   libsystem_kernel.dylib          0x3b8178f10         mach_msg2_internal
2   libsystem_kernel.dylib          0x3b8178e28         mach_msg_overwrite
3   libsystem_kernel.dylib          0x3b8178c68         mach_msg
4   CoreFoundation                  0x329329b1c         <redacted>
5   CoreFoundation                  0x329327a14         <redacted>
6   CoreFoundation                  0x329327478         CFRunLoopRunSpecific
7   CFNetwork                       0x32b706060         estimatedPropertyListSize
8   Foundation                      0x3272d7de0         <redacted>
9   libsystem_pthread.dylib         0x3fd30e4d4         _pthread_start

Thread 18 name: JSC Heap Collector Thread
0   libsystem_kernel.dylib          0x3b8179b1c         __psynch_cvwait
1   libsystem_pthread.dylib         0x3fd30cfd4         <redacted>
2   JavaScriptCore                  0x354893120         WTF::ThreadCondition::timedWait
3   JavaScriptCore                  0x35486c1d4         WTF::ParkingLot::parkConditionallyImpl
4   JavaScriptCore                  0x35482a728         <redacted>
5   JavaScriptCore                  0x354890334         <redacted>
6   JavaScriptCore                  0x35489280c         <redacted>
7   libsystem_pthread.dylib         0x3fd30e4d4         _pthread_start

Thread 19
0   libsystem_kernel.dylib          0x3b8179178         mach_msg2_trap
1   libsystem_kernel.dylib          0x3b8178f10         mach_msg2_internal
2   libsystem_kernel.dylib          0x3b8178e28         mach_msg_overwrite
3   libsystem_kernel.dylib          0x3b8178c68         mach_msg
4   libdispatch.dylib               0x339308f00         <redacted>
5   libdispatch.dylib               0x3393092a0         dispatch_mach_send_with_result_and_wait_for_reply
6   libxpc.dylib                    0x3fd3a26d4         xpc_connection_send_message_with_reply_sync
7   RunningBoardServices            0x34747a3d4         <redacted>
8   RunningBoardServices            0x34747a094         <redacted>
9   RunningBoardServices            0x34747a01c         <redacted>
10  RunningBoardServices            0x347472610         <redacted>
11  RunningBoardServices            0x3474722c4         <redacted>
12  WebKit                          0x353272dbc         <redacted>
13  WebKit                          0x35327ac14         <redacted>
14  JavaScriptCore                  0x3548c9090         <redacted>
15  libdispatch.dylib               0x3392ee300         <redacted>
16  libdispatch.dylib               0x3392f5894         <redacted>
17  libdispatch.dylib               0x3392f63c4         <redacted>
18  libdispatch.dylib               0x339301004         <redacted>
19  libdispatch.dylib               0x339300878         <redacted>
20  libsystem_pthread.dylib         0x3fd30d964         _pthread_wqthread

Thread 20
0   libsystem_kernel.dylib          0x3b8179978         __semwait_signal
1   libsystem_c.dylib               0x339381f20         nanosleep
2   libsystem_c.dylib               0x3393901dc         sleep
3   SenseCAPMate                    0x20107e5e8         facebook::react::JSIExecutor::defaultTimeoutInvoker
4   libsystem_pthread.dylib         0x3fd30e4d4         _pthread_start

Thread 21
0   libsystem_kernel.dylib          0x3b8179178         mach_msg2_trap
1   libsystem_kernel.dylib          0x3b8178f10         mach_msg2_internal
2   libsystem_kernel.dylib          0x3b8178e28         mach_msg_overwrite
3   libsystem_kernel.dylib          0x3b8178c68         mach_msg
4   SenseCAPMate                    0x201089f84         __cxa_throw
5   libsystem_pthread.dylib         0x3fd30e4d4         _pthread_start

Thread 23
0   libsystem_kernel.dylib          0x3b8179978         __semwait_signal
1   libsystem_c.dylib               0x339381f20         nanosleep
2   Foundation                      0x32796e76c         <redacted>
3   SenseCAPMate                    0x20106f668         facebook::react::JSIExecutor::defaultTimeoutInvoker
4   Foundation                      0x3272d7de0         <redacted>
5   libsystem_pthread.dylib         0x3fd30e4d4         _pthread_start


OS Version: iOS 17.2 (21C5054b)
Report Version: 104

Exception Type: EXC_BAD_ACCESS (SIGBUS)
Exception Codes: BUS_NOOP at 0x0000000000000018
Crashed Thread: 0

Application Specific Information:
ZTUM >
Attempted to dereference garbage pointer 0x18.

Thread 0 Crashed:
0   SenseCAPMate                    0x200eecc18         folly::detail::str_to_integral<T>
1   SenseCAPMate                    0x200f14b48         folly::detail::str_to_integral<T>
2   libdispatch.dylib               0x3392ec6a8         <redacted>
3   libdispatch.dylib               0x3392ee300         <redacted>
4   libdispatch.dylib               0x3392fc998         <redacted>
5   libdispatch.dylib               0x3392fc5b0         _dispatch_main_queue_callback_4CF
6   CoreFoundation                  0x32932b01c         <redacted>
7   CoreFoundation                  0x329327d28         <redacted>
8   CoreFoundation                  0x329327478         CFRunLoopRunSpecific
9   Foundation                      0x32725448c         <redacted>
10  Foundation                      0x32728174c         <redacted>
11  SenseCAPMate                    0x2011c00a0         __cxa_throw
12  SenseCAPMate                    0x200d033c8         <redacted>
13  UIKitCore                       0x32d965fd0         <redacted>
14  UIKitCore                       0x32d965138         <redacted>
15  UIKitCore                       0x32d96411c         <redacted>
16  UIKitCore                       0x32d963d68         <redacted>
17  UIKitCore                       0x32d8e0890         _UIScenePerformActionsWithLifecycleActionMask
18  UIKitCore                       0x32d967d64         <redacted>
19  UIKitCore                       0x32d88f700         <redacted>
20  UIKitCore                       0x32d88e178         <redacted>
21  UIKitCore                       0x32d88dae0         <redacted>
22  UIKitCore                       0x32d88d9b0         <redacted>
23  UIKitCore                       0x32d88d8b8         <redacted>
24  UIKitCore                       0x32d88d140         _UISceneSettingsDiffActionPerformChangesWithTransitionContextAndCompletion
25  UIKitCore                       0x32d88cdf0         <redacted>
26  UIKitCore                       0x32dc10314         <redacted>
27  UIKitCore                       0x32d88bf74         <redacted>
28  UIKitCore                       0x32d88bde4         <redacted>
29  UIKitCore                       0x32d9a477c         <redacted>
30  UIKitCore                       0x32d9a4514         <redacted>
31  FrontBoardServices              0x359c436d4         <redacted>
32  FrontBoardServices              0x359c43570         <redacted>
33  FrontBoardServices              0x359c4219c         <redacted>
34  FrontBoardServices              0x359c4df8c         <redacted>
35  libdispatch.dylib               0x3392ee300         <redacted>
36  libdispatch.dylib               0x3392f1d48         <redacted>
37  FrontBoardServices              0x359c3e520         <redacted>
38  FrontBoardServices              0x359c3e4a0         <redacted>
39  FrontBoardServices              0x359c3e378         <redacted>
40  CoreFoundation                  0x32932b12c         <redacted>
41  CoreFoundation                  0x32932a3a8         <redacted>
42  CoreFoundation                  0x329328b5c         <redacted>
43  CoreFoundation                  0x329327898         <redacted>
44  CoreFoundation                  0x329327478         CFRunLoopRunSpecific
45  GraphicsServices                0x3afe594f8         GSEventRunModal
46  UIKitCore                       0x32d981360         <redacted>
47  UIKitCore                       0x32d98099c         UIApplicationMain
48  SenseCAPMate                    0x200d0397c         <redacted>
49  <unknown>                       0x1c42fddcc         <redacted>

Thread 0 Crashed:
0   SenseCAPMate                    0x200eecc18         folly::detail::str_to_integral<T>
1   SenseCAPMate                    0x200f14b48         folly::detail::str_to_integral<T>
2   libdispatch.dylib               0x3392ec6a8         <redacted>
3   libdispatch.dylib               0x3392ee300         <redacted>
4   libdispatch.dylib               0x3392fc998         <redacted>
5   libdispatch.dylib               0x3392fc5b0         _dispatch_main_queue_callback_4CF
6   CoreFoundation                  0x32932b01c         <redacted>
7   CoreFoundation                  0x329327d28         <redacted>
8   CoreFoundation                  0x329327478         CFRunLoopRunSpecific
9   Foundation                      0x32725448c         <redacted>
10  Foundation                      0x32728174c         <redacted>
11  SenseCAPMate                    0x2011c00a0         __cxa_throw
12  SenseCAPMate                    0x200d033c8         <redacted>
13  UIKitCore                       0x32d965fd0         <redacted>
14  UIKitCore                       0x32d965138         <redacted>
15  UIKitCore                       0x32d96411c         <redacted>
16  UIKitCore                       0x32d963d68         <redacted>
17  UIKitCore                       0x32d8e0890         _UIScenePerformActionsWithLifecycleActionMask
18  UIKitCore                       0x32d967d64         <redacted>
19  UIKitCore                       0x32d88f700         <redacted>
20  UIKitCore                       0x32d88e178         <redacted>
21  UIKitCore                       0x32d88dae0         <redacted>
22  UIKitCore                       0x32d88d9b0         <redacted>
23  UIKitCore                       0x32d88d8b8         <redacted>
24  UIKitCore                       0x32d88d140         _UISceneSettingsDiffActionPerformChangesWithTransitionContextAndCompletion
25  UIKitCore                       0x32d88cdf0         <redacted>
26  UIKitCore                       0x32dc10314         <redacted>
27  UIKitCore                       0x32d88bf74         <redacted>
28  UIKitCore                       0x32d88bde4         <redacted>
29  UIKitCore                       0x32d9a477c         <redacted>
30  UIKitCore                       0x32d9a4514         <redacted>
31  FrontBoardServices              0x359c436d4         <redacted>
32  FrontBoardServices              0x359c43570         <redacted>
33  FrontBoardServices              0x359c4219c         <redacted>
34  FrontBoardServices              0x359c4df8c         <redacted>
35  libdispatch.dylib               0x3392ee300         <redacted>
36  libdispatch.dylib               0x3392f1d48         <redacted>
37  FrontBoardServices              0x359c3e520         <redacted>
38  FrontBoardServices              0x359c3e4a0         <redacted>
39  FrontBoardServices              0x359c3e378         <redacted>
40  CoreFoundation                  0x32932b12c         <redacted>
41  CoreFoundation                  0x32932a3a8         <redacted>
42  CoreFoundation                  0x329328b5c         <redacted>
43  CoreFoundation                  0x329327898         <redacted>
44  CoreFoundation                  0x329327478         CFRunLoopRunSpecific
45  GraphicsServices                0x3afe594f8         GSEventRunModal
46  UIKitCore                       0x32d981360         <redacted>
47  UIKitCore                       0x32d98099c         UIApplicationMain
48  SenseCAPMate                    0x200d0397c         <redacted>
49  <unknown>                       0x1c42fddcc         <redacted>

Thread 1
0   libsystem_pthread.dylib         0x3fd30d9fc         _pthread_wqthread

Thread 2
0   libsystem_kernel.dylib          0x3b81816d0         __workq_kernreturn
1   libsystem_pthread.dylib         0x3fd30d9b0         _pthread_wqthread

Thread 3
0   libquic.dylib                   0x4087d9034         <redacted>
1   libquic.dylib                   0x4087d8f98         [inlined] <redacted>
2   libquic.dylib                   0x4087d8f98         <redacted>
3   Network                         0x32a37d9d0         nw_frame_array_foreach
4   libquic.dylib                   0x4087d8f14         <redacted>
5   Network                         0x32a048764         nw_protocol_instance_access_flow_state
6   libquic.dylib                   0x4087d8d78         <redacted>
7   libquic.dylib                   0x4087d8b10         <redacted>
8   libboringssl.dylib              0x38a188228         <redacted>
9   libboringssl.dylib              0x38a1c3d60         <redacted>
10  libboringssl.dylib              0x38a1761e4         <redacted>
11  libboringssl.dylib              0x38a15624c         <redacted>
12  libboringssl.dylib              0x38a163ddc         SSL_do_handshake
13  libboringssl.dylib              0x38a163b38         boringssl_session_handshake_continue
14  libboringssl.dylib              0x38a14b42c         <redacted>
15  libboringssl.dylib              0x38a163aac         <redacted>
16  libboringssl.dylib              0x38a180da0         <redacted>
17  Network                         0x329da8358         nw_queue_context_async_if_needed
18  libboringssl.dylib              0x38a180548         <redacted>
19  CFNetwork                       0x32b5682d0         CFURLDownloadStart
20  CFNetwork                       0x32b685a34         CFHTTPCookieStorageUnscheduleFromRunLoop
21  CFNetwork                       0x32b5575a4         CFURLDownloadStart
22  CFNetwork                       0x32b557248         CFURLDownloadStart
23  libdispatch.dylib               0x3392ec6a8         <redacted>
24  libdispatch.dylib               0x3392ee300         <redacted>
25  libdispatch.dylib               0x3392f5894         <redacted>
26  libdispatch.dylib               0x3392f63f8         <redacted>
27  libdispatch.dylib               0x3392f76a8         <redacted>
28  libdispatch.dylib               0x339301004         <redacted>
29  libdispatch.dylib               0x339300878         <redacted>
30  libsystem_pthread.dylib         0x3fd30d964         _pthread_wqthread

Thread 4 name: com.apple.uikit.eventfetch-thread
0   libsystem_kernel.dylib          0x3b8179178         mach_msg2_trap
1   libsystem_kernel.dylib          0x3b8178f10         mach_msg2_internal
2   libsystem_kernel.dylib          0x3b8178e28         mach_msg_overwrite
3   libsystem_kernel.dylib          0x3b8178c68         mach_msg
4   CoreFoundation                  0x329329b1c         <redacted>
5   CoreFoundation                  0x329327a14         <redacted>
6   CoreFoundation                  0x329327478         CFRunLoopRunSpecific
7   Foundation                      0x32725448c         <redacted>
8   Foundation                      0x32728174c         <redacted>
9   UIKitCore                       0x32d8e30c0         <redacted>
10  Foundation                      0x3272d7de0         <redacted>
11  libsystem_pthread.dylib         0x3fd30e4d4         _pthread_start

Thread 5
0   CoreFoundation                  0x329308758         <redacted>
1   CoreFoundation                  0x3293086a4         <redacted>
2   CoreFoundation                  0x3293f886c         <redacted>
3   CoreFoundation                  0x329309930         <redacted>
4   CoreFoundation                  0x32935cb70         _CFPropertyListCreateFiltered
5   CoreFoundation                  0x32938db34         <redacted>
6   CoreFoundation                  0x32936eefc         <redacted>
7   CoreFoundation                  0x329350264         <redacted>
8   CoreFoundation                  0x32934fb88         _CFBundleCopyLocalizedStringForLocalizationTableURLAndMarkdownOption
9   CFNetwork                       0x32b588b0c         _CFURLWriteDataAndPropertiesToResource
10  CFNetwork                       0x32b588278         _CFURLWriteDataAndPropertiesToResource
11  libsystem_pthread.dylib         0x3fd30f3d4         <redacted>
12  libsystem_platform.dylib        0x3fd1b7eb4         <redacted>
13  libsystem_pthread.dylib         0x3fd30f7a8         pthread_once
14  CFNetwork                       0x32b588188         _CFURLWriteDataAndPropertiesToResource
15  CFNetwork                       0x32b4ae814         _CFNetworkErrorCopyLocalizedDescriptionWithHostname
16  Foundation                      0x3278d73bc         <redacted>
17  Foundation                      0x3278d75f4         <redacted>
18  Foundation                      0x3278d71fc         <redacted>
19  CFNetwork                       0x32b4d8314         CFHTTPMessageCopySerializedMessage
20  libdispatch.dylib               0x3392ec6a8         <redacted>
21  libdispatch.dylib               0x3392ee300         <redacted>
22  libdispatch.dylib               0x3392f5894         <redacted>
23  libdispatch.dylib               0x3392f63f8         <redacted>
24  libdispatch.dylib               0x339301004         <redacted>
25  libdispatch.dylib               0x339300878         <redacted>
26  libsystem_pthread.dylib         0x3fd30d964         _pthread_wqthread

Thread 6
0   libsystem_kernel.dylib          0x3b81790f4         semaphore_wait_trap
1   libdispatch.dylib               0x3392ee89c         <redacted>
2   libdispatch.dylib               0x3392eef4c         <redacted>
3   CFNetwork                       0x32b4b0718         CFURLConnectionSendSynchronousRequest
4   CFNetwork                       0x32b570910         cfnTranslateCFError
5   SenseCAPMate                    0x2012685d0         __cxa_throw
6   SenseCAPMate                    0x201265540         __cxa_throw
7   SenseCAPMate                    0x20126cf54         __cxa_throw
8   libdispatch.dylib               0x3392ec6a8         <redacted>
9   libdispatch.dylib               0x3392ee300         <redacted>
10  libdispatch.dylib               0x3392f144c         <redacted>
11  libdispatch.dylib               0x3392ffbe4         <redacted>
12  libdispatch.dylib               0x3393003ec         <redacted>
13  libsystem_pthread.dylib         0x3fd30d928         _pthread_wqthread

Thread 7
0   libsystem_pthread.dylib         0x3fd30d9fc         _pthread_wqthread

Thread 8
0   libsystem_kernel.dylib          0x3b81816d0         __workq_kernreturn
1   libsystem_pthread.dylib         0x3fd30d9b0         _pthread_wqthread

Thread 9
0   libsystem_pthread.dylib         0x3fd30d9fc         _pthread_wqthread

Thread 10 name: com.facebook.react.JavaScript
0   libsystem_kernel.dylib          0x3b8179178         mach_msg2_trap
1   libsystem_kernel.dylib          0x3b8178f10         mach_msg2_internal
2   libsystem_kernel.dylib          0x3b8178e28         mach_msg_overwrite
3   libsystem_kernel.dylib          0x3b8178c68         mach_msg
4   CoreFoundation                  0x329329b1c         <redacted>
5   CoreFoundation                  0x329327a14         <redacted>
6   CoreFoundation                  0x329327478         CFRunLoopRunSpecific
7   SenseCAPMate                    0x200f682d4         facebook::react::JSIExecutor::defaultTimeoutInvoker
8   Foundation                      0x3272d7de0         <redacted>
9   libsystem_pthread.dylib         0x3fd30e4d4         _pthread_start

Thread 11 name: JavaScriptCore libpas scavenger
0   libsystem_kernel.dylib          0x3b8179b1c         __psynch_cvwait
1   libsystem_pthread.dylib         0x3fd30cfd4         <redacted>
2   JavaScriptCore                  0x355da31a0         <redacted>
3   libsystem_pthread.dylib         0x3fd30e4d4         _pthread_start

Thread 12 name: Heap Helper Thread
0   libsystem_kernel.dylib          0x3b8179b1c         __psynch_cvwait
1   libsystem_pthread.dylib         0x3fd30cfd4         <redacted>
2   JavaScriptCore                  0x354893120         WTF::ThreadCondition::timedWait
3   JavaScriptCore                  0x35486c1d4         WTF::ParkingLot::parkConditionallyImpl
4   JavaScriptCore                  0x35482a728         <redacted>
5   JavaScriptCore                  0x354890334         <redacted>
6   JavaScriptCore                  0x35489280c         <redacted>
7   libsystem_pthread.dylib         0x3fd30e4d4         _pthread_start

Thread 13 name: Heap Helper Thread
0   libsystem_kernel.dylib          0x3b8179b1c         __psynch_cvwait
1   libsystem_pthread.dylib         0x3fd30cfd4         <redacted>
2   JavaScriptCore                  0x354893120         WTF::ThreadCondition::timedWait
3   JavaScriptCore                  0x35486c1d4         WTF::ParkingLot::parkConditionallyImpl
4   JavaScriptCore                  0x35482a728         <redacted>
5   JavaScriptCore                  0x354890334         <redacted>
6   JavaScriptCore                  0x35489280c         <redacted>
7   libsystem_pthread.dylib         0x3fd30e4d4         _pthread_start

Thread 14 name: Heap Helper Thread
0   libsystem_kernel.dylib          0x3b8179b1c         __psynch_cvwait
1   libsystem_pthread.dylib         0x3fd30cfd4         <redacted>
2   JavaScriptCore                  0x354893120         WTF::ThreadCondition::timedWait
3   JavaScriptCore                  0x35486c1d4         WTF::ParkingLot::parkConditionallyImpl
4   JavaScriptCore                  0x35482a728         <redacted>
5   JavaScriptCore                  0x354890334         <redacted>
6   JavaScriptCore                  0x35489280c         <redacted>
7   libsystem_pthread.dylib         0x3fd30e4d4         _pthread_start

Thread 15 name: Heap Helper Thread
0   libsystem_kernel.dylib          0x3b8179b1c         __psynch_cvwait
1   libsystem_pthread.dylib         0x3fd30cfd4         <redacted>
2   JavaScriptCore                  0x354893120         WTF::ThreadCondition::timedWait
3   JavaScriptCore                  0x35486c1d4         WTF::ParkingLot::parkConditionallyImpl
4   JavaScriptCore                  0x35482a728         <redacted>
5   JavaScriptCore                  0x354890334         <redacted>
6   JavaScriptCore                  0x35489280c         <redacted>
7   libsystem_pthread.dylib         0x3fd30e4d4         _pthread_start

Thread 16 name: Heap Helper Thread
0   libsystem_kernel.dylib          0x3b8179b1c         __psynch_cvwait
1   libsystem_pthread.dylib         0x3fd30cfd4         <redacted>
2   JavaScriptCore                  0x354893120         WTF::ThreadCondition::timedWait
3   JavaScriptCore                  0x35486c1d4         WTF::ParkingLot::parkConditionallyImpl
4   JavaScriptCore                  0x35482a728         <redacted>
5   JavaScriptCore                  0x354890334         <redacted>
6   JavaScriptCore                  0x35489280c         <redacted>
7   libsystem_pthread.dylib         0x3fd30e4d4         _pthread_start

Thread 17 name: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib          0x3b8179178         mach_msg2_trap
1   libsystem_kernel.dylib          0x3b8178f10         mach_msg2_internal
2   libsystem_kernel.dylib          0x3b8178e28         mach_msg_overwrite
3   libsystem_kernel.dylib          0x3b8178c68         mach_msg
4   CoreFoundation                  0x329329b1c         <redacted>
5   CoreFoundation                  0x329327a14         <redacted>
6   CoreFoundation                  0x329327478         CFRunLoopRunSpecific
7   CFNetwork                       0x32b706060         estimatedPropertyListSize
8   Foundation                      0x3272d7de0         <redacted>
9   libsystem_pthread.dylib         0x3fd30e4d4         _pthread_start

Thread 18 name: JSC Heap Collector Thread
0   libsystem_kernel.dylib          0x3b8179b1c         __psynch_cvwait
1   libsystem_pthread.dylib         0x3fd30cfd4         <redacted>
2   JavaScriptCore                  0x354893120         WTF::ThreadCondition::timedWait
3   JavaScriptCore                  0x35486c1d4         WTF::ParkingLot::parkConditionallyImpl
4   JavaScriptCore                  0x35482a728         <redacted>
5   JavaScriptCore                  0x354890334         <redacted>
6   JavaScriptCore                  0x35489280c         <redacted>
7   libsystem_pthread.dylib         0x3fd30e4d4         _pthread_start

Thread 19
0   libsystem_kernel.dylib          0x3b8179178         mach_msg2_trap
1   libsystem_kernel.dylib          0x3b8178f10         mach_msg2_internal
2   libsystem_kernel.dylib          0x3b8178e28         mach_msg_overwrite
3   libsystem_kernel.dylib          0x3b8178c68         mach_msg
4   libdispatch.dylib               0x339308f00         <redacted>
5   libdispatch.dylib               0x3393092a0         dispatch_mach_send_with_result_and_wait_for_reply
6   libxpc.dylib                    0x3fd3a26d4         xpc_connection_send_message_with_reply_sync
7   RunningBoardServices            0x34747a3d4         <redacted>
8   RunningBoardServices            0x34747a094         <redacted>
9   RunningBoardServices            0x34747a01c         <redacted>
10  RunningBoardServices            0x347472610         <redacted>
11  RunningBoardServices            0x3474722c4         <redacted>
12  WebKit                          0x353272dbc         <redacted>
13  WebKit                          0x35327ac14         <redacted>
14  JavaScriptCore                  0x3548c9090         <redacted>
15  libdispatch.dylib               0x3392ee300         <redacted>
16  libdispatch.dylib               0x3392f5894         <redacted>
17  libdispatch.dylib               0x3392f63c4         <redacted>
18  libdispatch.dylib               0x339301004         <redacted>
19  libdispatch.dylib               0x339300878         <redacted>
20  libsystem_pthread.dylib         0x3fd30d964         _pthread_wqthread

Thread 20
0   libsystem_kernel.dylib          0x3b8179978         __semwait_signal
1   libsystem_c.dylib               0x339381f20         nanosleep
2   libsystem_c.dylib               0x3393901dc         sleep
3   SenseCAPMate                    0x20107e5e8         facebook::react::JSIExecutor::defaultTimeoutInvoker
4   libsystem_pthread.dylib         0x3fd30e4d4         _pthread_start

Thread 21
0   libsystem_kernel.dylib          0x3b8179178         mach_msg2_trap
1   libsystem_kernel.dylib          0x3b8178f10         mach_msg2_internal
2   libsystem_kernel.dylib          0x3b8178e28         mach_msg_overwrite
3   libsystem_kernel.dylib          0x3b8178c68         mach_msg
4   SenseCAPMate                    0x201089f84         __cxa_throw
5   libsystem_pthread.dylib         0x3fd30e4d4         _pthread_start

Thread 23
0   libsystem_kernel.dylib          0x3b8179978         __semwait_signal
1   libsystem_c.dylib               0x339381f20         nanosleep
2   Foundation                      0x32796e76c         <redacted>
3   SenseCAPMate                    0x20106f668         facebook::react::JSIExecutor::defaultTimeoutInvoker
4   Foundation                      0x3272d7de0         <redacted>
5   libsystem_pthread.dylib         0x3fd30e4d4         _pthread_start

I think I may have just gotten this error in prod with RNScreens 3.27 and Reanimated 3.5.4 (RN 0.72.5):
Does this error seem like it came from Reanimated?
@tomekzaw

**Comment by tomekzaw** [comment]
@zhou0506 No, there's no "reanimated" or "screens" anywhere in the stack trace.

**Comment by tomekzaw** [comment]
@jamogon On what exactly?
