### ISSUE TITLE
KeyboardAvodingView implemented with useAnimatedKeyboard doesn't work after 3.0.0-rc.10

### ISSUE THREAD

**Issue by terrysahaidak** [software-mansion/react-native-reanimated#4324]
### Description

After upgrading to the latest Reanimated version (for my tests i used the latest commit as for today `2d3016b8dcc482f51422c144eef58bf4657b7792`) and my custom implementation of KeyboardAvoidingView doesn't always work.

Here you can see that the log inside of `useAnimatedStyle` is reporting changes for the `keyboard.height`, but the actual change is not applied to the view until i click somewhere. The same happens when i call `Keyboard.dismiss()`.

If was working in `3.0.0-rc.10`.

But when the scroll view by dragging dismissing the keyboard it actually animates the height.

https://user-images.githubusercontent.com/7809008/229533865-d473bf5f-fca3-4b5c-a02f-ca2750d3352b.mov

### Steps to reproduce

1. Click on the input
2. Click somewhere in the screen for the styles to update
3. Click on dismiss
4. Click somewhere to apply the styles
5. Do it again but now drag the scroll view

### Snack or a link to a repository

https://github.com/terrysahaidak/UseAnimatedKeyboardBug1

### Reanimated version

3.0.2 and `2d3016b8dcc482f51422c144eef58bf4657b7792` commit

### React Native version

0.71.5

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @terrysahaidak, thanks for opening this issue, we will take care of this.

**Comment by tomekzaw** [comment]
@terrysahaidak Thanks again for reporting the issue and providing a helpful reproducer.

I believe this issue has been fixed with #4266 and #4329 which was merged recently.

It looks like the problem you have mentioned does no longer occur on 2fe3e3882548ab18c86849e7e279ed20cd204e3a. Here's a video recording:

https://user-images.githubusercontent.com/20516055/230062129-ba17e50b-d576-445a-b595-f420fecceff5.mp4

<br />
Watching the video in slow motion, there's still 1-2 frames of delay but this is a separate issue and we're actively working on it, so I'm closing this issue. Thanks again!

**Comment by terrysahaidak** [comment]
Nice! Thanks a lot! Any ETA for the new Reanimated release?

**Comment by tomekzaw** [comment]
@terrysahaidak Not decided yet but probably next week

**Comment by hirbod** [comment]
Ah dang it, just stumbled across this issue. But glad it has been fixed. I haven't checked the PRs yet, but is this also going to be backported for REA2?

**Comment by hirbod** [comment]
We're still not able to upgrade to v3 in our project. It would be convenient, since I have the same issue on v2 but if your schedule is tight, I would instead use https://github.com/kirillzyusko/react-native-keyboard-controller which I have used in the past (before there was useAnimatedKeyboard)
