### ISSUE TITLE
Runtime Error - New Arch - Shared Value in a Context

### ISSUE THREAD

**Issue by AlirezaHadjar** [software-mansion/react-native-reanimated#5472]
### Description

I just created a newly initialized repo and after installing reanimated, I added a `React Context` which had a `SharedValue` inside. But I faced an error.

```groovy
 ERROR  Error: Exception in HostFunction: java.lang.NoSuchFieldError: no "Lcom/facebook/react/fabric/BindingImpl;" field "mBinding" in class "Lcom/facebook/react/fabric/FabricUIManager;" or its superclasses, js engine: hermes 
    at Provider (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.reanimatedrn73&modulesOnly=false&runModule=true:125621:24)
    at App (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.reanimatedrn73&modulesOnly=false&runModule=true:125633:44)
    at RCTView
    at View (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.reanimatedrn73&modulesOnly=false&runModule=true:60140:43)
    at RCTView
    at View (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.reanimatedrn73&modulesOnly=false&runModule=true:60140:43)
    at AppContainer (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.reanimatedrn73&modulesOnly=false&runModule=true:59982:36)
    at reanimatedRN73(RootComponent) (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.reanimatedrn73&modulesOnly=false&runModule=true:111133:28)
 ERROR  Error: Exception in HostFunction: java.lang.NoSuchFieldError: no "Lcom/facebook/react/fabric/BindingImpl;" field "mBinding" in class "Lcom/facebook/react/fabric/FabricUIManager;" or its superclasses, js engine: hermes 
    at Provider (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.reanimatedrn73&modulesOnly=false&runModule=true:125621:24)
    at App (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.reanimatedrn73&modulesOnly=false&runModule=true:125633:44)
    at RCTView
    at View (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.reanimatedrn73&modulesOnly=false&runModule=true:60140:43)
    at RCTView
    at View (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.reanimatedrn73&modulesOnly=false&runModule=true:60140:43)
    at AppContainer (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.reanimatedrn73&modulesOnly=false&runModule=true:59982:36)
    at reanimatedRN73(RootComponent) (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.reanimatedrn73&modulesOnly=false&runModule=true:111133:28)
 ERROR  Error: Exception in HostFunction: java.lang.NoSuchFieldError: no "Lcom/facebook/react/fabric/BindingImpl;" field "mBinding" in class "Lcom/facebook/react/fabric/FabricUIManager;" or its superclasses, js engine: hermes 
    at Provider (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.reanimatedrn73&modulesOnly=false&runModule=true:125621:24)
    at App (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.reanimatedrn73&modulesOnly=false&runModule=true:125633:44)
    at RCTView
    at View (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.reanimatedrn73&modulesOnly=false&runModule=true:60140:43)
    at RCTView
    at View (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.reanimatedrn73&modulesOnly=false&runModule=true:60140:43)
    at AppContainer (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.reanimatedrn73&modulesOnly=false&runModule=true:59982:36)
    at reanimatedRN73(RootComponent) (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.reanimatedrn73&modulesOnly=false&runModule=true:111133:28)
 ERROR  Error: Exception in HostFunction: java.lang.NoSuchFieldError: no "Lcom/facebook/react/fabric/BindingImpl;" field "mBinding" in class "Lcom/facebook/react/fabric/FabricUIManager;" or its superclasses, js engine: hermes 
    at Provider (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.reanimatedrn73&modulesOnly=false&runModule=true:125621:24)
    at App (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.reanimatedrn73&modulesOnly=false&runModule=true:125633:44)
    at RCTView
    at View (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.reanimatedrn73&modulesOnly=false&runModule=true:60140:43)
    at RCTView
    at View (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.reanimatedrn73&modulesOnly=false&runModule=true:60140:43)
    at AppContainer (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.reanimatedrn73&modulesOnly=false&runModule=true:59982:36)
    at reanimatedRN73(RootComponent) (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.reanimatedrn73&modulesOnly=false&runModule=true:111133:28)
 ERROR  TypeError: Cannot read property 'makeMutable' of undefined

This error is located at:
    in Provider (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in reanimatedRN73(RootComponent), js engine: hermes
 ERROR  TypeError: Cannot read property 'makeMutable' of undefined

This error is located at:
    in Provider (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in reanimatedRN73(RootComponent), js engine: hermes
```
<img width="559" alt="Screenshot 2023-12-07 at 2 33 41 PM" src="https://github.com/software-mansion/react-native-reanimated/assets/57192409/57e14a37-9bc2-46a2-a4cd-90f2aea8e155">

### Steps to reproduce

1. Initialize a repo:
```sh 
npx react-native@latest init reanimatedRN73
```
2. Install `react-native-reanimated`:
```sh 
yarn add react-native-reanimated
```
2.1. Added the `reanimated` plugin

3. Enable `New Architecture`:
```gradle
newArchEnabled=true
```
4. Start the Android build:
```sh 
yarn android
```
5. Added a simple `React Context` which had a `SharedValue` inside:
```tsx
import React from 'react';
import {useSharedValue} from 'react-native-reanimated';

const Context = React.createContext({});

const Provider = ({children}: {children: React.ReactNode}) => {
  const value = useSharedValue(1);

  return <Context.Provider value={{}}>{children}</Context.Provider>;
};

const App: React.FC = ({}) => {
  return <Provider />;
};

export default App;

```

### Snack or a link to a repository

https://github.com/AlirezaHadjar/reanimatedRN73.git

### Reanimated version

3.6.1

### React Native version

0.73.0

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

Debug app & dev bundle

### Device

Android emulator

### Device model

Nexus 5X

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
@AlirezaHadjar Thank you for submitting this issue and providing a detailed description.

This is an error in React Native 0.73.0 itself and happens only on Android with Fabric enabled. 

This error is already investigated and fixed by @piaskowyk in https://github.com/facebook/react-native/pull/41657 but unfortunately wasn't picked for 0.73.0 although we specifically asked for it here: https://github.com/reactwg/react-native-releases/discussions/64#discussioncomment-7693949.

According to @huntie, it should be picked for 0.73.1: https://github.com/reactwg/react-native-releases/discussions/64#discussioncomment-7716778.

**Comment by AnuMessi10** [comment]
@tomekzaw facing this in `0.72.7` as well, any workarounds?

**Comment by tomekzaw** [comment]
@AnuMessi10 you can apply the change from https://github.com/facebook/react-native/pull/41657 and build React Native from sources as described [here](https://reactnative.dev/contributing/how-to-build-from-source#update-your-project-to-build-from-source)

**Comment by ahmetbicer** [comment]
@tomekzaw Hi, I upgraded my app to React Native 0.73.1. It fixed the issue in the debug variant, but I'm still facing the same problem in the release. Do you have any idea what the issue might be?

`Fatal Exception: com.facebook.react.common.JavascriptException: Error: Exception in HostFunction: java.lang.NoSuchFieldError: no type "Lcom/facebook/react/fabric/Binding;" found and so no field "mBinding" could be found in class "Lcom/facebook/react/fabric/FabricUIManager;" or its superclasses, js engine: hermes`

**Comment by migueldaipre** [comment]
> @tomekzaw Hi, I upgraded my app to React Native 0.73.1. It fixed the issue in the debug variant, but I'm still facing the same problem in the release. Do you have any idea what the issue might be?
> 
> `Fatal Exception: com.facebook.react.common.JavascriptException: Error: Exception in HostFunction: java.lang.NoSuchFieldError: no type "Lcom/facebook/react/fabric/Binding;" found and so no field "mBinding" could be found in class "Lcom/facebook/react/fabric/FabricUIManager;" or its superclasses, js engine: hermes`

Fixed by #5550
