### ISSUE TITLE
debuggerWorker.js:69 TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by TonyFTannous-Byd** [software-mansion/react-native-reanimated#6432]
### Description

![352525954-22331002-5e09-405b-a1a4-d439aec6f2e6](https://github.com/user-attachments/assets/a6e26434-e90d-4faf-bae3-da14b0b81f54)

### Steps to reproduce

i use react native 0.75.1, when launching react native debugger, this error displayed and the app crashed

### Snack or a link to a repository

https://github.com/software-mansion/react-native-reanimated

### Reanimated version

^3.15.0

### React Native version

0.75.1

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by MatiPl01** [comment]
Hey!

Could you pleas provide more information? Did you use the new (experimental) react native debugger, chrome debugger or some other debugging tool?

Can you provide a repro or share the repository?

**Comment by TonyFTannous-Byd** [comment]
i user react native debugger [https://github.com/jhen0409/react-native-debugger](url) because it support debug request network.
i use react native 0.75.1, and i need to debug my request network. so i used react native debugger with enabled network inspect. because i use @react-navigation/drawer which it use react-native-reanimated 3.15.0. an error occured: Cannot convert undefined or null to object located in /node_modules/react-native-reanimated/src/js-reanimated/index.ts --> _updatePropsJS --> component.props

**Comment by MatiPl01** [comment]
Thank you for response. I can reproduce the issue while I am debugging JS remotely with `react-native-debugger`. I am not sure it we will able to fix that, though, as this debugger doesn't support JSI, which reanimated uses.

From the `react-native-debugger` README:

> ⚠️ This app is currently only supported old [Remote Debugger](https://reactnative.dev/docs/debugging#chrome-developer-tools), if you're looking for new debugger support (e.g. Hermes / JSI / New Architecture) of React Native Debugger, please follow https://github.com/jhen0409/react-native-debugger/discussions/774.

I will look into this issue and check it we can do something.

**Comment by MatiPl01** [comment]
@TonyFTannous-Byd Could you check if changes I made in the #6437 PR fix your issue? You can make the same changes in `node_modules/react-native-reanimated` and see if you still see this error.

If you still have some problems, don't hesitate to re-open the issue and ask.

**Comment by abdulmoizshaikh** [comment]
Hello @MatiPl01 ,
I was facing the same problem as @TonyFTannous-Byd mentioned and opened this ticket

I tried the fix that you have created and merge in this PR [6437](https://github.com/software-mansion/react-native-reanimated/pull/6437)

This issue of `debuggerWorker.js:69 TypeError: Cannot convert undefined or null to object` is fixed now

But now when I connected with debugger my Tab navigation is not working
whereas drawer and stack navigation is working fine.

**Comment by MatiPl01** [comment]
Hey @abdulmoizshaikh!

Would you be able to share your code or a small repro showing the issue? Not everything will work while you use remote JS debugging but I will check what we can do if you share some code.

**Comment by TonyFTannous-Byd** [comment]
hey @MatiPl01 
i use the last version of react-native-reanimated ^3.15.3, and the issue still exists when using @react-navigation/drawer

**Comment by MatiPl01** [comment]
Hey @TonyFTannous-Byd!

Yes, it was merged. If you still encounter this problem, can you please open a new issue and describe it more in detail (I mean, include some repro or code snippet that causes this error)?

**Comment by TonyFTannous** [comment]
hello @MatiPl01 

you can use this repo: https://github.com/TonyFTannous/TemplateTest.git
1- download it
2- npm install
3- npm run start:clean:8082
5- npm run debugger:8082   
6- npm run android:local:8082  or  npm run ios:local:8082
7- after launch, please go the index.js remove the comment of the following line

    line 6 --> import {NativeModules} from 'react-native';

    line 17, 18, 19 --> 
        if (__DEV__) {
            NativeModules.DevSettings.setIsDebuggingRemotely(true);
        }

**then save to connect to debugger.
When connected, recomment it to prevent reloading periodically**

when login screen displayed, enter any email and any password to login, when you login after a bit of second the issues appear

**Comment by TonyFTannous** [comment]
Hello @MatiPl01 , any news concerning this issue

**Comment by MatiPl01** [comment]
Hey @TonyFTannous!

I am very sorry for the late response but I was busy working on some other things and missed your previous comment. I've just checked that my change wasn't included in latest patch reanimated releases. We are planning to release `3.16.0` within a few days so I think you can wait for the next minor release and my fix will be included.

If you need it working now, please look at my [PR](https://github.com/software-mansion/react-native-reanimated/pull/6437/files) and patch the `react-native-reanimated` library with the same changes as I made in this PR.

**Comment by TonyFTannous** [comment]
hello @MatiPl01 , thanks a lot for your help.
i install the version 3.15.4 and i patch the library locally. The issue solved 👍, **but the animation became so slow when open/close the drawer**
please let me know when the library is ready, to test it

**Comment by MatiPl01** [comment]
Hey @TonyFTannous!

I want to let you know that the `3.16.0` version of reanimated was released today. It took some more time that we expected to release the new version that includes these changes but they are rolled out now, so you should be able to test them.

> but the animation became so slow when open/close the drawer Android Platform

It is likely due to the fact that reanimated uses a separate thread during the normal usage, where all animations are executed. When you run reanimated with a react native debugger, reanimated is executed on the JS thread, thus everything runs slower. I think there is no much we can do with this.

**Comment by TonyFTannous-Byd** [comment]
Hey @MatiPl01 
Thank you so much. good job.
concerning the slowing, noted. and it is only on android emulator, on ios is working normaly.
👍

**Comment by priyankfz7** [comment]
hello @MatiPl01 I am using current version "react-native-reanimated": "^3.16.7", i am able to connect my debugger but its network tab is not working
