### ISSUE TITLE
[Android][New Arch] Buttons inside Animated.View with translate are not clickable 

### ISSUE THREAD

**Issue by delphinebugner** [software-mansion/react-native-reanimated#6676]
### Description

On my app, I have buttons inside Animated Views that translate up. 
Right after the translation finished, the pressable action of the button is not executed on click. 
If we execute another action (ex. navigating on an other tab and come back), the pressable action is executed on click. 

This is what we see on the repro below: 

![ReproButtonReanimated](https://github.com/user-attachments/assets/a36e90a1-023f-49b6-9c13-fab03aafb8fc)

Additional notes: 

- New Arch + Android only
- On **real device** only, not on emulator (😅 really weird)
- Pressable and Buttons have the same error
- Pressable and Buttons variable opacity _are_ triggered when we click the first time; only the `onPress` callback is'nt triggered
- On an animated view with only a variable _opacity_, no error; it's linked to the translation operation

### Code

Code looks like this:
```typescript
export const AnimatedButton = () => {
  const shiftAmount = useSharedValue(-100);
  const shiftDownStyle = useAnimatedStyle(() => ({
    transform: [{ translateY: shiftAmount.value }],
  }));

  if (shiftAmount.value !== 0) {
    shiftAmount.value = withTiming(0, { duration: 450 });
  }

  return (
    <Animated.View style={shiftDownStyle}>
      <Button
        title="Press me"
        onPress={() => Alert.alert("Im clicked")} // 🚨 not triggered the first time
      />
    </Animated.View>
  );
```

A full example can be found here: https://github.com/delphinebugner/repro

### Further notes

Thanks for working on the lib 🙂

If the problem is linked to a messy Reanimated usage in the component, happy to correct my code! 

### Steps to reproduce

On the [repro application](https://github.com/delphinebugner/repro):

1. Run it on a **real** device (error does not occur on emulator)
2. Just after mounting the Home, try to clic on a "Press me" button : nothing happens 🚨 
3. Click on "Explore" Tab
4. Return to "Home" Tab
5. Click on a "Press me" button: an alert shows up ✅ 
6. Click on the "Toggle animated buttons" to unmount-remount them
7. Click again a "Press me" button: nothing happens 🚨 

### Snack or a link to a repository

https://github.com/delphinebugner/repro

### Reanimated version

3.16.1

### React Native version

0.75.0

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

Expo Dev Client

### Architecture

Fabric (New Architecture)

### Build type

Debug app & dev bundle

### Device

Real device

### Device model

Samsung Galaxy S22

### Acknowledgements

Yes

**Comment by JoaoMosmann** [comment]
I had a similar problem. To fix it I had to use the `Pressable` component exported by the `react-native-gesture-handler` library.

**Comment by smfunder** [comment]
I have a similar issue, basically I use 'react-native-popover-view' to list a menu with TouchableOpacity from react elements. When I try to press them after showing the popup which uses Animated.View elements inside (pure TypeScript, no native stuff) they are not pressable at all.
I tried with the @JoaoMosmann suggestion for the buttons, but they are not working in my case.
This is happening to me only in Android 13.
"react-native-reanimated": "^3.17.0-rc.0",
 "react-native": "0.76.3" (New Arch + bridgeless mode)
Any ideas?

**Comment by DarkShtir** [comment]
same issue

**Comment by JaewooSeo-mnetplus** [comment]
same issue

**Comment by mluksha** [comment]
The same

**Comment by tomekzaw** [comment]
@j-piasecki reported another issue with root cause explanation: 
https://github.com/software-mansion/react-native-reanimated/issues/6832

**Comment by tomekzaw** [comment]
Should be fixed with https://github.com/software-mansion/react-native-reanimated/pull/7014.

**Comment by delphinebugner** [comment]
Thanks for the fix @tomekzaw & @j-piasecki 🙏 Do you have an idea on when it will be released? 

I have issues with [KeyboardStickyView](https://kirillzyusko.github.io/react-native-keyboard-controller/docs/api/components/keyboard-sticky-view) of react-native-keyboard-controller - Text input inside becomes un-clickable on Android (sometimes).

As the `KeyboardStickyView` is just a Reanimated View interpolating keyboard animation, could it have from the same root cause?

**Comment by HugoGresse** [comment]
would love to see this patch applied to v3. Having a beta dependencies in our app freak me out. I'll do a .patch but as it's cpp code I'm unsure it is a good idea. 
For now I'll probably remove the animation, as Pressable from `react-native-gesture-handler` does not look identical from RN.

**Comment by tomekzaw** [comment]
@HugoGresse This patch has been already backported to v3, please try upgrading to `react-native-reanimated@3.17.5`.

**Comment by HugoGresse** [comment]
Thank you Tomasz for the quick answer! 
I was already on 3.17.5 but I still have the issue. Redone a `rm -rf node_modules`, `npm start --reset-cache` and install on android on my physical device and the issue persist. 
Weirdly enough, the issue happen on a Samsung s23 running android 14, but not on the Pixel 8a emulated on android 16.

**Comment by tomekzaw** [comment]
@HugoGresse Okay, so this sounds like another issue, this time it's an issue in React Native itself. Can you please try the workaround described in this comment and let me know if it helps? https://github.com/software-mansion/react-native-reanimated/issues/6935#issuecomment-2829785177

**Comment by HugoGresse** [comment]
Woot! Thank you Tomasz, you aere right!

**Comment by Sky** [comment]
Same here, we upgraded to RN 0.79.2, enabled those flags but this does not fix the issue on Android. We use `Animated.ScrollView` and change `translateY` and after scrolling neither `Pressable` or `TouchableOpacity` from RN will not trigger `onPress` when tapped but `onPressIn` and `onPressOut` is triggered.

**Comment by HugoGresse** [comment]
linked issue https://github.com/software-mansion/react-native-reanimated/issues/6704
