### ISSUE TITLE
Crash on first start (Reanimated 4 supports only the React Native New Architecture)

### ISSUE THREAD

**Issue by iMakarenkoSeverex** [software-mansion/react-native-reanimated#8235]
### Description

In the release build on a real device (always) and sometimes on the emulator, the application crashes on the first launch on a splash screen. On subsequent launches, everything is fine.

info from crashlytics:

`
ReanimatedError: [Reanimated] Reanimated 4 supports only the React Native New Architecture and web., js engine: hermes, stack: ReanimatedErrorConstructor@1:998922 NativeReanimatedModule@1:1184108 createNativeReanimatedModule@1:1183208 anonymous@1:1177541 loadModuleImplementation@1:51733 guardedLoadModule@1:51257 metroRequire@1:50853 get@1:1177442 anonymous@1:986194 loadModuleImplementation@1:51733 guardedLoadModule@1:51257 metroRequire@1:50853 anonymous@1:978022 loadModuleImplementation@1:51733 guardedLoadModule@1:51257 metroRequire@1:50853 anonymous@1:897844 loadModuleImplementation@1:51733 guardedLoadModule@1:51257 metroRequire@1:50853 anonymous@1:895336 loadModuleImplementation@1:51733 guardedLoadModule@1:51257 metroRequire@1:50853 anonymous@1:894845 loadModuleImplementation@1:51733 guardedLoadModule@1:51257 metroRequire@1:50853 anonymous@1:828330 loadModuleImplementation@1:51733 guardedLoadModule@1:51257 metroRequire@1:50853 anonymous@1:827728 loadModuleImplementation@1:51733 guardedLoadModule@1:51257 metroRequire@1:50853 anonymous@1:734721 loadModuleImplementation@1:51733 guardedLoadModule@1:51257 metroRequire@1:50853 anonymous@1:58299 loadModuleImplementation@1:51733 guardedLoadModule@1:51214 metroRequire@1:50853 global@1:50375
`

setup:
```
babel.config.js
module.exports = {
  presets: ['module:@react-native/babel-preset'],
  plugins: ['react-native-worklets/plugin'],
};
```

    "react-native": "0.80.2",
    "react-native-reanimated": "^4.0.2",
    "react-native-worklets": "^0.4.1",

newArchEnabled=true
hermesEnabled=true

if prompted in console  i see these parameters:
`console.error: globalThis.RN$Bridgeless true, js engine: hermes, ...`
`console.error: SHOULD_BE_USE_WEB false, js engine: hermes,...`

### Steps to reproduce

no

### Snack or a link to a repository

no

### Reanimated version

4.0.2

### Worklets version

0.4.1

### React Native version

0.80.2

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native CLI

### Architecture

New Architecture (Fabric renderer)

### Build type

Release app & production bundle

### Device

Real device

### Host machine

macOS

### Acknowledgements

Yes

**Comment by tadeumelembe** [comment]
Same here

**Comment by Vashiru** [comment]
Yep, same, app where I have newArchEnabled=true, upgraded to react-native-reanimated v4. But mine isn't just a single one time on start-up, mine keeps crashing even on subsequent start-ups

**Comment by fnxlsjfl** [comment]
Same here. Even if I upgrade version to 4.1.0, the crash still happens once.

**Comment by fnxlsjfl** [comment]
I've downgraded version to 3.18.0, it seems work.

**Comment by Kakaranara** [comment]
This issue (crash) also appears when we receive a pop-up from a push notification. (tested in android)

**Comment by syaKainew** [comment]
> Yep, same, app where I have newArchEnabled=true, upgraded to react-native-reanimated v4. But mine isn't just a single one time on start-up, mine keeps crashing even on subsequent start-ups

I encountered the same problem, have you solved it?

**Comment by syaKainew** [comment]
When building with expo everything works fine (expo run:android) 
When building with eas the build is successful but after installation on physical devices it crashes, this started happening after updating to expo 54 and reanimated 4.1

Logcat: 09-17 10:22:41.858 F/libc    ( 6903): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 6943 (pool-11-thread-), pid 6903 (com.my.app) 

`plugins: [
      [
        'module:react-native-dotenv',
        {
          moduleName: '@env'
        }
      ],
      '@lingui/babel-plugin-lingui-macro',
      'react-native-worklets/plugin'
    ]`

` "dependencies": {
    "@expo/vector-icons": "^15.0.2",
    "@freakycoder/react-native-bounceable": "^2.0.0",
    "@gorhom/bottom-sheet": "^5.0.6",
    "@lingui/core": "^5.4.1",
    "@lingui/react": "^5.4.1",
    "@react-native-async-storage/async-storage": "2.2.0",
    "@react-native-community/netinfo": "11.4.1",
    "@react-native-firebase/app": "^23.3.1",
    "@react-navigation/bottom-tabs": "^7.2.0",
    "@react-navigation/material-top-tabs": "^7.2.9",
    "@react-navigation/native": "^7.1.17",
    "@react-navigation/native-stack": "^7.1.6",
    "@react-navigation/stack": "^7.0.6",
    "@sentry/react-native": "~6.20.0",
    "@shopify/flash-list": "2.0.2",
    "axios": "^1.7.7",
    "date-fns": "^4.1.0",
    "expo": "54.0.8",
    "expo-blur": "~15.0.7",
    "expo-camera": "~17.0.8",
    "expo-checkbox": "~5.0.7",
    "expo-doctor": "^1.17.7",
    "expo-file-system": "~19.0.14",
    "expo-font": "~14.0.8",
    "expo-haptics": "~15.0.7",
    "expo-localization": "~17.0.7",
    "expo-notifications": "^0.32.11",
    "expo-secure-store": "~15.0.7",
    "expo-sensors": "~15.0.7",
    "expo-splash-screen": "~31.0.10",
    "expo-status-bar": "~3.0.8",
    "expo-system-ui": "~6.0.7",
    "intl-messageformat": "^10.7.14",
    "libphonenumber-js": "^1.12.17",
    "lottie-react-native": "~7.3.1",
    "react": "19.1.0",
    "react-native": "0.81.4",
    "react-native-compressor": "^1.12.0",
    "react-native-confirmation-code-field": "^7.4.0",
    "react-native-country-codes-picker": "^2.3.5",
    "react-native-country-flag": "^2.0.2",
    "react-native-device-info": "^14.0.4",
    "react-native-dotenv": "^3.4.11",
    "react-native-dynamic-search-bar": "^2.0.2",
    "react-native-element-dropdown": "^2.12.4",
    "react-native-elements": "^3.4.3",
    "react-native-gesture-handler": "~2.28.0",
    "react-native-is-edge-to-edge": "^1.2.1",
    "react-native-keyboard-controller": "1.18.5",
    "react-native-modal": "^13.0.1",
    "react-native-page-indicator": "^2.4.2",
    "react-native-pager-view": "6.9.1",
    "react-native-reanimated": "^4.1.0",
    "react-native-safe-area-context": "^5.6.1",
    "react-native-screens": "^4.16.0",
    "react-native-spinkit": "^1.5.1",
    "react-native-svg": "15.12.1",
    "react-native-ui-datepicker": "^3.1.2",
    "react-native-uuid": "^2.0.3",
    "react-native-webview": "13.15.0",
    "react-native-worklets": "0.5.1"
  }`

for the sake of experiment, I created a project with almost empty logic, and the result was the same (I didn't delete any files from the project, and I removed all imports, leaving only react-native)

`<Viev>
<Text>TEST</Text>
</View>`

**Comment by Vashiru** [comment]
> > Yep, same, app where I have newArchEnabled=true, upgraded to react-native-reanimated v4. But mine isn't just a single one time on start-up, mine keeps crashing even on subsequent start-ups
> 
> I encountered the same problem, have you solved it?

No, I figured it's a bug in the library that will get resolved over time. There's no need for me to upgrade to v4.x right now, I was just pro-actively upgrading things. Same reason I'm sticking to RN 0.80 for now as RN 0.81 triggers [#3643 in react-native-gesture-handler](https://github.com/software-mansion/react-native-gesture-handler/issues/3643). (Dunno if that still gets triggered on v4 because of the crash).

**Comment by krunalinfynno** [comment]
+1

**Comment by WilliamsDima** [comment]
+1

**Comment by rafaeIrf** [comment]
+1

**Comment by rayProground** [comment]
+1

**Comment by syaKainew** [comment]
Hi, it only worked for me after I initialized a new expo project and installed all the modules again. Try running a clean project, it might help you.

**Comment by developerUnit-cmd** [comment]
any update on this ?

**Comment by WilliamsDima** [comment]
A new version was just released. I cleared the cache and reinstalled node modules. The error is gone. Try this version.

"react-native-reanimated": "^4.1.1"

**Comment by Pingou** [comment]
Can anyone else confirm that 4.1.1 fixes the issue?

**Comment by anh-tuan03** [comment]
> Can anyone else confirm that 4.1.1 fixes the issue?

I don't think so, i upgraded to Reanimated v4.1.2 and have this issue, downgrade to v4.1.1, delete everything & clean cache then rebuild and still have the same issue. But i can confirm the error only appear when i first install the app on emulator

```
com.facebook.react.common.JavascriptException: [Reanimated] Reanimated 4 supports only the React Native New Architecture and web., stack:
ReanimatedError: [Reanimated] Reanimated 4 supports only the React Native New Architecture and web.
    at ReanimatedErrorConstructor (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.app.agency&modulesOnly=false&runModule=true&excludeSource=true&sourcePaths=url-server:98493:36)
    at NativeReanimatedModule (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.app.agency&modulesOnly=false&runModule=true&excludeSource=true&sourcePaths=url-server:106795:80)
    at createNativeReanimatedModule (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.app.agency&modulesOnly=false&runModule=true&excludeSource=true&sourcePaths=url-server:106742:38)
    at anonymous (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.app.agency&modulesOnly=false&runModule=true&excludeSource=true&sourcePaths=url-server:104548:287)
    at loadModuleImplementation (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.app.agency&modulesOnly=false&runModule=true&excludeSource=true&sourcePaths=url-server:267:14)
    at guardedLoadModule (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.app.agency&modulesOnly=false&runModule=true&excludeSource=true&sourcePaths=url-server:175:38)
    at metroRequire (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.app.agency&modulesOnly=false&runModule=true&excludeSource=true&sourcePaths=url-server:89:92)
    at get (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.app.agency&modulesOnly=false&runModule=true&excludeSource=true&sourcePaths=url-server:104537:25)
    at anonymous (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.app.agency&modulesOnly=false&runModule=true&excludeSource=true&sourcePaths=url-server:97564:138)
    at loadModuleImplementation (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.app.agency&modulesOnly=false&runModule=true&excludeSource=true&sourcePaths=url-server:267:14)
    at guardedLoadModule (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.app.agency&modulesOnly=false&runModule=true&excludeSource=true&sourcePaths=url-server:175:38)
    at metroRequire (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.app.agency&modulesOnly=false&runModule=true&excludeSource=true&sourcePaths=url-server:89:92)
    at anonymous (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.app.agency&modulesOnly=false&runModule=true&excludeSource=true&sourcePaths=url-server:1280:14)
    at loadModuleImplementation (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.app.agency&modulesOnly=false&runModule=true&excludeSource=true&sourcePaths=url-server:267:14)
    at guardedLoadModule (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.app.agency&modulesOnly=false&runModule=true&excludeSource=true&sourcePaths=url-server:168:47)
    at metroRequire (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.app.agency&modulesOnly=false&runModule=true&excludeSource=true&sourcePaths=url-server:89:92)
    at global (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.app.agency&modulesOnly=false&runModule=true&excludeSource=true&sourcePaths=url-server:398863:4)
	at com.facebook.jni.NativeRunnable.run(Native Method)
2025-10-02 10:30:12.577 27307-27424 unknown:ReactNative     com.app.agency                    E  	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl.lambda$startNewBackgroundThread$2(MessageQueueThreadImpl.java:217)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)
2025-10-02 10:30:12.584 27307-27424 ReactNativeJNI          com.app.agency                    E  Attempting to call JS function on a bad application bundle: RCTDeviceEventEmitter.emit()
2025-10-02 10:30:12.590 27307-27424 unknown:ReactNative     com.app.agency                    E  Exception in native call
java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: RCTDeviceEventEmitter.emit()
	at com.facebook.jni.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl.lambda$startNewBackgroundThread$2(MessageQueueThreadImpl.java:217)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)
2025-10-02 10:30:12.591 27307-27424 ReactNativeJNI          com.app.agency                    E  Attempting to call JS function on a bad application bundle: RCTDeviceEventEmitter.emit()
```

**Comment by ridho-badr** [comment]
is there any updated everyone?

**Comment by aminhdev** [comment]
+1

**Comment by anh-tuan03** [comment]
Can try upgrade worklets to compatible version with reanimated v4.x.x

> react-native-worklets: 0.5.1

I don't see the old error `Reanimated 4 supports only the React Native New Architecture and web` anymore, can anyone confirm it for me ?

Also, the crash still persist with a new error:

```
2025-10-09 16:30:02.554 10817-10817 AndroidRuntime          com.app.agency                    E  FATAL EXCEPTION: main
Process: com.app.agency, PID: 10817
java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference in method 'void android.view.ViewGroup.dispatchGetDisplayList()'
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4493)
	at android.view.View.updateDisplayListIfDirty(View.java:23646)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
	at android.view.View.updateDisplayListIfDirty(View.java:23646)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
	at android.view.View.updateDisplayListIfDirty(View.java:23646)
```

More insight: This error seem to relate with entering or existing prop of any animated components, i did try to remove the existing at some component and did see the appear rate go down, but not entirely sure due to other place also use those props but didn't have the error.
The error mostly appear at the first install and open app, it also occasionally appear at other place

**Comment by MykytaShchukin** [comment]
> 
> ```
> 2025-10-09 16:30:02.554 10817-10817 AndroidRuntime          com.app.agency                    E  FATAL EXCEPTION: main
> Process: com.app.agency, PID: 10817
> java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference in method 'void android.view.ViewGroup.dispatchGetDisplayList()'
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4493)
> 	at android.view.View.updateDisplayListIfDirty(View.java:23646)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
> 	at android.view.View.updateDisplayListIfDirty(View.java:23646)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
> 	at android.view.View.updateDisplayListIfDirty(View.java:23646)
> ```
> 
> More insight: This error seem to relate with entering or existing prop of any animated components, i did try to remove the existing at some component and did see the appear rate go down, but not entirely sure due to other place also use those props but didn't have the error. The error mostly appear at the first install and open app, it also occasionally appear at other place




Also have this issue with NullPointerException.
any updates?

**Comment by likesebiii** [comment]
Any update on this? I still see the int android.view.View.mViewFlags error in production.

`NullPointerException: Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference in method 'void android.view.ViewGroup.dispatchGetDisplayList()'`

**Comment by Paul12pp** [comment]
I'm having this issue on release version PROD,
"react-native-reanimated": "4.1.3",
"react-native": "0.81.4",

**Comment by Zunaira-Haroon** [comment]
I'm facing same issue on ios.
The application crashes on the first launch with  --> react_native_assert(isBridgeless && "[Worklets] react-native-worklets only supports bridgeless mode");

"react-native-reanimated": "^4.1.3",
"react-native": "0.81.4",
"react-native-worklets": "^0.6.1",

**Comment by Pingou** [comment]
Can anyone from software-mansion chime in? @tjzel? On firebase this crash has thousands of events for me and is responsible for 95% of my crashes, although it only affects a small portion of my users.

**Comment by tjzel** [comment]
Fixed with #8406

**Comment by Pingou** [comment]
> Fixed with [#8406](https://github.com/software-mansion/react-native-reanimated/pull/8406)

Thanks a lot! When can we expect a release?

**Comment by anh-tuan03** [comment]
> Fixed with [#8406](https://github.com/software-mansion/react-native-reanimated/pull/8406)

That is awesome, thank you. When is the release of the fixed issue ?

**Comment by rpyoyo** [comment]
> Fixed with [#8406](https://github.com/software-mansion/react-native-reanimated/pull/8406)

<img width="1722" height="958" alt="Image" src="https://github.com/user-attachments/assets/996fb72d-b6cd-4ae1-9105-9977ab5814aa" />

I patched the package locally and test again, the crash still happens.

**Comment by Pingou** [comment]
> > Fixed with [#8406](https://github.com/software-mansion/react-native-reanimated/pull/8406)
> 
> <img alt="Image" width="1722" height="958" src="https://private-user-images.githubusercontent.com/4035181/502966119-996fb72d-b6cd-4ae1-9105-9977ab5814aa.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjA4NzE3NTEsIm5iZiI6MTc2MDg3MTQ1MSwicGF0aCI6Ii80MDM1MTgxLzUwMjk2NjExOS05OTZmYjcyZC1iNmNkLTRhZTEtOTEwNS05OTc3YWI1ODE0YWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTAxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEwMTlUMTA1NzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzliYWZiZjZhMDkyYTcyYWY5OWEyMTg4NzI5M2Y0Nzk3YjQ0MzNkNTkzZWE4NGQxMDkwNjkzNTYxNjg5OTU3NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.3Dges0XW_F_7V-U7qedvbaXI3CqJ2yE5C1-ydDJgt1U">
> I patched the package locally and test again, the crash still happens.

Try patching that file: node_modules/react-native-reanimated/lib/module/ReanimatedModule/NativeReanimated.js

**Comment by rpyoyo** [comment]
> > > Fixed with [#8406](https://github.com/software-mansion/react-native-reanimated/pull/8406)
> > 
> > 
> > <img alt="Image" width="1722" height="958" src="https://private-user-images.githubusercontent.com/4035181/502966119-996fb72d-b6cd-4ae1-9105-9977ab5814aa.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjA4NzE3NTEsIm5iZiI6MTc2MDg3MTQ1MSwicGF0aCI6Ii80MDM1MTgxLzUwMjk2NjExOS05OTZmYjcyZC1iNmNkLTRhZTEtOTEwNS05OTc3YWI1ODE0YWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTAxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEwMTlUMTA1NzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzliYWZiZjZhMDkyYTcyYWY5OWEyMTg4NzI5M2Y0Nzk3YjQ0MzNkNTkzZWE4NGQxMDkwNjkzNTYxNjg5OTU3NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.3Dges0XW_F_7V-U7qedvbaXI3CqJ2yE5C1-ydDJgt1U">
> > I patched the package locally and test again, the crash still happens.
> 
> Try patching that file: node_modules/react-native-reanimated/lib/module/ReanimatedModule/NativeReanimated.js

I just patched the file node_modules/react-native-reanimated/lib/module/ReanimatedModule/NativeReanimated.js, but the app still crashes. I wonder if the RN$Bridgeless assertion is really related to this issue. As @anh-tuan03 mentioned above, the crash error seems to be related to the entering or exiting prop of any animated components. After I removed the exiting prop, the crash didn't happen.

**Comment by Pingou** [comment]
Can confirm that the patch doesn't fix the crash. @tjzel ?

**Comment by tjzel** [comment]
@Pingou React Native pulls library files from source first, a patch to the source file, not only generated `lib/module` is necessary.

This is the patch you have to apply

```diff
diff --git a/node_modules/react-native-reanimated/lib/module/ReanimatedModule/NativeReanimated.js b/node_modules/react-native-reanimated/lib/module/ReanimatedModule/NativeReanimated.js
index 7ee916a..1c088fd 100644
--- a/node_modules/react-native-reanimated/lib/module/ReanimatedModule/NativeReanimated.js
+++ b/node_modules/react-native-reanimated/lib/module/ReanimatedModule/NativeReanimated.js
@@ -47,7 +47,7 @@ class NativeReanimatedModule {
       throw new ReanimatedError(`Native part of Reanimated doesn't seem to be initialized.
 See https://docs.swmansion.com/react-native-reanimated/docs/guides/troubleshooting#native-part-of-reanimated-doesnt-seem-to-be-initialized for more details.`);
     }
-    if (!globalThis.RN$Bridgeless && !SHOULD_BE_USE_WEB) {
+    if (__DEV__ && !globalThis.RN$Bridgeless && !SHOULD_BE_USE_WEB) {
       throw new ReanimatedError('Reanimated 4 supports only the React Native New Architecture and web.');
     }
     if (__DEV__) {
diff --git a/node_modules/react-native-reanimated/src/ReanimatedModule/NativeReanimated.ts b/node_modules/react-native-reanimated/src/ReanimatedModule/NativeReanimated.ts
index 0d3fe2e..c8b6f92 100644
--- a/node_modules/react-native-reanimated/src/ReanimatedModule/NativeReanimated.ts
+++ b/node_modules/react-native-reanimated/src/ReanimatedModule/NativeReanimated.ts
@@ -83,7 +83,7 @@ class NativeReanimatedModule implements IReanimatedModule {
 See https://docs.swmansion.com/react-native-reanimated/docs/guides/troubleshooting#native-part-of-reanimated-doesnt-seem-to-be-initialized for more details.`
       );
     }
-    if (!globalThis.RN$Bridgeless && !SHOULD_BE_USE_WEB) {
+    if (__DEV__ && !globalThis.RN$Bridgeless && !SHOULD_BE_USE_WEB) {
       throw new ReanimatedError(
         'Reanimated 4 supports only the React Native New Architecture and web.'
       );
```

**Comment by RodolfoSilva** [comment]
> Can try upgrade worklets to compatible version with reanimated v4.x.x
> 
> > react-native-worklets: 0.5.1
> 
> I don't see the old error `Reanimated 4 supports only the React Native New Architecture and web` anymore, can anyone confirm it for me ?
> 
> Also, the crash still persist with a new error:
> 
> ```
> 2025-10-09 16:30:02.554 10817-10817 AndroidRuntime          com.app.agency                    E  FATAL EXCEPTION: main
> Process: com.app.agency, PID: 10817
> java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference in method 'void android.view.ViewGroup.dispatchGetDisplayList()'
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4493)
> 	at android.view.View.updateDisplayListIfDirty(View.java:23646)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
> 	at android.view.View.updateDisplayListIfDirty(View.java:23646)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
> 	at android.view.View.updateDisplayListIfDirty(View.java:23646)
> ```
> 
> More insight: This error seem to relate with entering or existing prop of any animated components, i did try to remove the existing at some component and did see the appear rate go down, but not entirely sure due to other place also use those props but didn't have the error. The error mostly appear at the first install and open app, it also occasionally appear at other place

I think this PR will solve this issue:

https://github.com/software-mansion/react-native-screens/pull/3322

Here is the issue: https://github.com/software-mansion/react-native-screens/issues/3321

**Comment by n9lsjr** [comment]
Still getting this error with 4.1.5 👎 

RN 0.79.6
Android AVD

**Comment by timmyjose** [comment]
That's not good to hear, @n9lsjr. I was hoping `4.1.5` would have the fix.

**Comment by n9lsjr** [comment]
I will try to upgrade RN to 0.80 + and give you more feedback 👍 And do some digging of my own 👍
